### ISSUE TITLE
Move CSS string from <body> to <head>

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#1]
There was a related question on the sphinx-users mailing list, but no solution:

https://groups.google.com/forum/?nomobile=true#!searchin/sphinx-users/css/sphinx-users/iG0fB9-JdNM/Le-rz_zbRHUJ

Also, the CSS string should only be included in the pages which actually need it.

**Comment by mgeier** [comment]
This can probably done with the `extrahead` block in `layout.html`, but it would be nice to be able to do that programmatically (without adding a separate template file).

**Comment by mgeier** [comment]
Since cdfd4f789b63c2817ba627eb42d26ac658f288ec, the CSS is only included for HTML files generated from notebooks (except if Sphinx version < 1.3.6 is used).

The CSS could also be added to `context['metatags']` instead of `context['body']`, but then it would end up very close to the top of the HTML file, which isn't too great either.
And I guess it is better to define the `nbsphinx` CSS *after* other CSS files are included ...

**Comment by tbekolay** [comment]
I just rebased the nbinclude stuff to master and cdfd4f7 kind of breaks it, in that the CSS doesn't get loaded so the included notebook looks bad. The `rst.rst` file in general doesn't work, as you can't manually use the `nbinput` or `nboutput` directives anymore without the CSS.

**Comment by mgeier** [comment]
Oh, sorry, I completely missed that!

I created a different solution in #37, can you please try if that works for you?

I'm not sure if that's a proper way to do that (see my doubts in #37), probably you know some improvements?
