### ISSUE TITLE
Control the behavior of toctree header

### ISSUE THREAD

**Issue by lordascor** [spatialaudio/nbsphinx#100]
Hi,

I'm facing a problem when using markdown headers in my notebooks:

Imagine I have a folder with severeal notebooks inside (I use the glob option in the toctree directive to show them on the html doc):

```
Folder
 +--- nbA.ipynb
 +--- nbB.ipynb
```

If there are different header levels, the output structure for the page "Folder" is:
```
Folder
 
Contents:
    nbA_1
        nbA_1-1
        nbA_1-2
    nbA_2
        nbA_2-1
    nbB_1
        nbB_1-1
        nbB_1-2
```
The problem is that the structure does not make a clear distinction of first level headings of different notebooks. What I would like to see is more like:

```
Folder
 
Contents:
    nbA
        nbA_1
            nbA_1-1
            nbA_1-2
        nbA_2
            nbA_2-1
    nbB
        nbB_1
            nbB_1-1
            nbB_1-2
```

The workaround for now is to have only one first level header to act as the notebook's title. I can't find any info on how we can actually control the way nbsphinx understands the markdown structure.

Is there something I can do to give the name of the notebook to nbsphinx to act as it's title in the toctree ?

**Comment by mgeier** [comment]
There is no such thing as a notebook title.
Neither is there a title in a "normal" Sphinx source file.
There are just different levels of headings.

But while in the Jupyter Notebook (and on nbviewer et al.) you will always get the *absolute* heading level you specified (according to the number of `#` signs), Sphinx ignores the absolute heading level and just creates one "tree" of headings (by creating nested "section" objects). See also https://github.com/spatialaudio/nbsphinx/issues/22#issuecomment-188890119.

I didn't come up with that, it's just what Sphinx does.

> The workaround for now is to have only one first level header to act as the notebook's title.

Yes, this is what I would do in most cases.

If you want to add another heading level "above" your notebook, you can add another source file with a sub-`toctree` which in turn includes your notebook. It would look like this: http://nbsphinx.readthedocs.io/en/latest/subdir/toctree.html.
The source file containing the `toctree` can be either an `.rst` file or an `.ipynb` file.
Another example for a sub-`toctree` is this page: http://nbsphinx.readthedocs.io/en/latest/executing-notebooks.html.

If you just want to change the appearance of the TOC (without changing the hierarchy of headings), you can use multiple `toctree` directives in a row, each with its own `:caption:` setting.
You can then style the `toctree` captions any way you like using a custom Sphinx theme.

Finally, you can use multiple `toctree` directives in a row, but add headings in-between. An additional level of headings in your index page will just push the headings of your notebooks one level down.

**Comment by mgeier** [comment]
@aaros-web Do you have any more comments on this?
Does it now work to your satisfaction?

**Comment by aaros-web** [comment]
@mgeier I didn't have the time to try the options you suggested. I know that the solution of having 1 source file pointing to the specific notebook won't satisfy my needs. Actually I'm putting a lot of notebooks in different folders and for each folder I have a single `.rst` file to populate the tree from the notebooks found inside. I will look into the other options.

Is it possible to use the `name` of the notebook (as in `name.ipynb`) to act as another level of headings ? Or having a meta-data item named "title" ?

**Comment by mgeier** [comment]
AFAIK know that's not possible in Sphinx. With `nbsphinx` your notebooks just become Sphinx source files. Their file name doesn't appear anywhere and I think there is no "title" meta-data, but you should check the Sphinx documentation for that.

You can also have a look at the alternatives to `nbsphinx`: http://nbsphinx.readthedocs.io/en/latest/links.html
Probably one of those allows you to do what you want?

**Comment by mgeier** [comment]
@aaros-web Any more comments? If not, I'll close this issue.
