### ISSUE TITLE
Latex: a line break should be added at the end of an adjacent ANSI cell 

### ISSUE THREAD

**Issue by Harlan-pku** [spatialaudio/nbsphinx#105]
Hi,

Thank you for this useful project. But when I built latex from a notebook, I found that adjacent ANSI cell wouldn't start a new line, so it would make something like this:

```latex
\begin{OriginalVerbatim}[commandchars=\\\{\}]
 some code
\end{OriginalVerbatim}\begin{itemize}
 some other code
\end{itemize}
```

In this example, the ``itemize `` cell won't be compiled correctly.

**Comment by mgeier** [comment]
Fixed in #107.
