### ISSUE TITLE
latex newcommand in markdown cell

### ISSUE THREAD

**Issue by gouarin** [spatialaudio/nbsphinx#109]
Hi,

I'm not sure that it is an issue but I didn't find informations about this problem.

So, I have a notebook with at the beginning a markdown cell with some latex newcommands defined like this

```
$$
\newcommand...
...
$$
```

It works fine when I use jupyter. All the newcommands are available for all the document. It also works if I use nbconvert.

But if I use nbsphinx and build the html version, the section with the newcommands are in a math div but there is no MathJax block.

What I'm doing wrong ?

Thanks,
Loic

**Comment by mgeier** [comment]
Thanks for this report.

Can you please provide a minimal example that shows this problem?

**Comment by gouarin** [comment]
You can find an example here

https://github.com/gouarin/nbsphinx_test

Thanks,
Loic

**Comment by mgeier** [comment]
Thanks, I'll look into it in the next few days.

**Comment by mgeier** [comment]
@gouarin

> What I'm doing wrong ?

Nothing at all.

It turns out that I made an error in #43.

You are using the `master` branch, right?
For now, you can get back to the latest released version, where your example should work as expected.

I'm working on a fix ...

**Comment by gouarin** [comment]
thanks @mgeier. I work with python 3.5 and nbsphinx 0.2.13 is installed using pip. 

So, the latest release also has this problem.

**Comment by mgeier** [comment]
@gouarin Right, I was confounding some dates. The error was released much earlier, I guess version 0.2.7 is a better guess for when it was introduced ...

I've tried to fix this bug in #110, can you please test if this works for you?

**Comment by gouarin** [comment]
Thanks !! It works for me with this pull request.

2017-04-09 18:48 GMT+02:00 Matthias Geier <notifications@github.com>:
