### ISSUE TITLE
Notebooks not executing

### ISSUE THREAD

**Issue by jnothman** [spatialaudio/nbsphinx#117]
Sorry if there's a better place to raise this.

I've tried to follow the setup instructions. The notebooks appear to be rendering, but don't appear to have been executed in documentation building (which I understand they should).

Is there a common cause of this? Is there a straightforward way to debug this?

**Comment by mgeier** [comment]
Did you read the documentation?

http://nbsphinx.readthedocs.io/en/latest/executing-notebooks.html

**Comment by jnothman** [comment]
I certainly tried to read but apparently missed the key point. I will send
a PR to try improve prominence.

**Comment by jnothman** [comment]
Would it be worth recommending a git smudge which clears output upon add?

**Comment by mgeier** [comment]
I think a full set of instructions how to use a smudge filter with Jupyter notebooks is out-of-scope for `nbsphinx`. But we could add a section on the "Usage" page about using Git, and there we could probably link so some blog post or tutorial where this might be explained in detail.
