### ISSUE TITLE
LaTeX: Images are too big

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#12]
I already [posted this on the Jupyter mailing list](https://groups.google.com/forum/#!topic/jupyter/TTMpJkem7jE), I'm just repeating it here:

The images (which look fine in the HTML output) are hideously large in the LaTeX output, see e.g.
https://media.readthedocs.org/pdf/nbsphinx/0.2.2/nbsphinx.pdf

This also happens with the "normal" nbconvert.

How can I get a reasonable image size?
Ideally this should work out-of-the box ...

I don't know if that's addressed already somewhere, I only found some mentions of image size in https://github.com/jupyter/nbconvert/pull/178 and https://gist.github.com/kroger/3856821.

Any further pointers would be very helpful!

**Comment by actsasgeek** [comment]
Has anyone resolved this? I'm noticing the same thing and I can't seem to do anything to fix it.

**Comment by mgeier** [comment]
It hasn't been resolved in `nbsphinx`, but there were some changes to `nbconvert` (see the link above, and there are probably further changes) which could probably be ported to `nbsphinx`.
@actsasgeek Do you want to give it a shot?

**Comment by mgeier** [comment]
I've created #222 to solve this, but there are still a few issues ...
