### ISSUE TITLE
cell output containing backslash letters

### ISSUE THREAD

**Issue by YiHoze** [spatialaudio/nbsphinx#122]
The output of  this code ``cd d:/temp`` in Jupyter is ``d:\temp``.
And that is rendered in Latex like this:

```
\begin{OriginalVerbatim}[commandchars=\\\{\}]
d:\temp
\end{OriginalVerbatim}
```
I think ``d\temp`` should be changed to ``d:\textbackslash{}temp``.
Is there any way to correct this problem?

@YiHoze

**Comment by mgeier** [comment]
Thanks for the report!

I've fixed this in #123, can you please check if it works for you?
