### ISSUE TITLE
Syntax highlighting in output cells

### ISSUE THREAD

**Issue by clenk** [spatialaudio/nbsphinx#124]
I have a Code cell with Python code that generates JSON output and would like the output to be syntax-highlighted. Is there a way to achieve this with `nbsphinx`?

**Comment by mgeier** [comment]
I'm currently on holidays, so I can't try it myself.
But I think there is nothing `nbsphinx`-specific to do this.

Can you achieve what you want in the live Notebook? Or with `nbconvert`?

Probably the answers here help:
https://stackoverflow.com/questions/19197931/how-to-show-as-output-cell-the-contents-of-a-py-file-with-syntax-highlighting

**Comment by clenk** [comment]
Okay, thanks for the info. Looks like it's not easily doable currently. There's a related nbconvert issue (https://github.com/jupyter/nbconvert/issues/363) but it seems to have stalled.
