### ISSUE TITLE
Ignore errors in a single cell

### ISSUE THREAD

**Issue by adrn** [spatialaudio/nbsphinx#125]
Is there currently a way to ignore errors produced by a single cell, or can it only be turned on globally or by notebook? If this isn't possible, it would be a nice feature to have - now that cells have their own metadata, it could be as simple as a check for:
```
"nbsphinx": {
  "allow_errors": true
},
```
at the cell-level metadata.

**Comment by adrn** [comment]
Hm, this may actually be an issue for nbconvert...

**Comment by mgeier** [comment]
Hm, this may actually be an issue for nbconvert...


nbsphinx is using nbconvert.preprocessors.ExecutePreprocessor to execute
the whole notebook at once.

So yes, I don't see a way to do this in nbsphinx itself, but if something
like this would be supported in nbconvert, it should automatically work in
nbsphinx, too.

**Comment by mgeier** [comment]
This seems to have been implemented in https://github.com/jupyter/nbconvert/pull/684.

@adrn Can you please check if it works for you?

**Comment by mgeier** [comment]
I have tried it and it seems to work, but the feature will only be available starting with `nbconvert` version 5.3, which isn't released yet.

I've created #158 to add documentation for this feature.
