### ISSUE TITLE
Exclude input/output prompt

### ISSUE THREAD

**Issue by adrn** [spatialaudio/nbsphinx#126]
Right now, as far as I can tell, there is no way to exclude the input or output prompt (the `In[...]:` and `Out[...]:`) from the rendered notebook pages. It looks like this is because they are added manually (instead of deferring to nbconvert; see [this line](https://github.com/spatialaudio/nbsphinx/blob/master/nbsphinx.py#L716)) so there is no way I can figure out to disable them (via the `TemplateExporter.exclude_input_prompt` and `TemplateExporter.exclude_output_prompt` [configuration options in nbconvert](http://nbconvert.readthedocs.io/en/latest/config_options.html)). Am I misunderstanding what's really happening? If it is not possible, it would be nice to have this as an option.

**Comment by mgeier** [comment]
If you are only targeting HTML, you can try setting nbsphinx_prompt_width
to 0.

See also https://github.com/spatialaudio/nbsphinx/issues/53

I would be interested in your motivations why you want to get rid of the
prompts.

And regarding TemplateExporter.exclude_input_prompt et al.: I'm open to a
PR that enables those options.

**Comment by adrn** [comment]
Setting `nbsphinx_prompt_width = 0` does seem to work.

**Comment by adrn** [comment]
(closing this because it seems like #131 addresses the broader idea of supporting `TemplateExporter` options)

**Comment by ferrine** [comment]
I used this formatting trick instead
```python
nbsphinx_input_prompt = "%.0s"
nbsphinx_output_prompt = "%.0s"
```

**Comment by mgeier** [comment]
Currently (nbsphinx version 0.9.1), the recommended way to remove the prompts in HTML output is via CSS:

```css
.nbinput .prompt,
.nboutput .prompt {
    display: none;
}
```

See https://nbsphinx.readthedocs.io/en/0.9.1/custom-css.html#For-a-Single-Notebook
