### ISSUE TITLE
Images not included

### ISSUE THREAD

**Issue by jgosmann** [spatialaudio/nbsphinx#169]
Images from plots created with Matplotlib and '%matplotlib inline' are not included in the generated documentation. I get warnings like
```
/home/jgosmann/Documents/projects/nengo_spa/docs/examples/vocabulary_casting.ipynb:: WARNING: image file not readable: examples/../_build/.doctrees/nbsphinx/examples_vocabulary_casting_7_1.png
```
even though the file reported an non-readable *does exist* and is readable.

**Comment by jgosmann** [comment]
This is with nbsphinx 0.3.1, sphinx 1.7.1, Matplotlib 2.1.0, and Python 3.6.1.

**Comment by mgeier** [comment]
Can you please provide an example notebook?

**Comment by jgosmann** [comment]
Example notebook can be found in nengo/nengo_spa#68, in particular [within this folder](https://github.com/nengo/nengo_spa/tree/45899bd5bba18ec276c01e0a3e642e00ac64d081/nengo_spa/examples). [Here is also the Sphinx configuration.](https://github.com/nengo/nengo_spa/blob/45899bd5bba18ec276c01e0a3e642e00ac64d081/docs/conf.py)

**Comment by mgeier** [comment]
OK, thanks, I guess this is a duplicate of #49?

**Comment by jgosmann** [comment]
Oops, you're right! I thought I wasn't using any symbolic links, but I checked again and turns out I was.
