### ISSUE TITLE
ENC: Hide Jupyter cell; retain output

### ISSUE THREAD

**Issue by par2** [spatialaudio/nbsphinx#17]
Is there a way to only output the result of a Jupyter cell, while hiding the code?  

The context is, I have plots that I would like to display as a gallery in rtds, but the code cells are distracting.  I'm not aware of this option to hide cells in Jupyter...  In fact, it looks like hiding input cells is on their [todo list](https://github.com/jupyter/notebook/issues/534) for 4.2. In the meantime,  in that same post, there is a hack for it.  

Your thoughts on adding this feature either now or in the future to nbsphinx...?

**Comment by mgeier** [comment]
This is a duplicate of #15, feel free to add your suggestions/comments there.

As a work-around for the use case you are describing, did you try to create the plots in a separate notebook (or stand-alone `.py` file) with `savefig()` and then use the generated image files in other parts of your docs?

**Comment by par2** [comment]
Yes I say that is an option.  Thanks.  I'll close this as it is a duplicate.
