### ISSUE TITLE
Underlined Headers

### ISSUE THREAD

**Issue by Olllom** [spatialaudio/nbsphinx#172]
This is a minor one.

I noticed that when I have underlined titles in a notebook's markdown cell the number signs appear in the toc.

For example,

```
## Some Title
---
```

gives
- \#\# Some Title

rather than
- Some Title

**Comment by mgeier** [comment]
Why would you write such a thing?
That doesn't make any sense.

Different Markdown parsers behave differently in this case: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23%23+Some+Title%0A---
But none of those gives the result you were expecting.

`nbsphinx` currently uses `pandoc`, but with #36 we probably switch to a CommonMark-compatible parser.
Either way, that doesn't change that the input is strange.
