### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by rddaz2013** [spatialaudio/nbsphinx#175]
How can I control the indent in the html output on output cell? (I have the "Out" Text removed )

In the latex Output i have some source code which are longer as 80 character - in the pdf there is no autowarp? How can i get this.

the release 0.3.2 works fine  :+1: 
i have my changes incorporated (hidden cell thing)

**Comment by mgeier** [comment]
> How can I control the indent in the html output on output cell?

Did you try `nbsphinx_prompt_width`?

> In the latex Output i have some source code which are longer as 80 character - in the pdf there is no autowarp? How can i get this.

Well the very best option would be to use not more than 80 characters per line!

Other than that, you can look if you find an option for that in the `fancyvrb` LaTeX package.

**Comment by rddaz2013** [comment]
Good points thx, i will try it.

**Comment by rddaz2013** [comment]
😎 sry on Holiday ... Next Week i Look into it



Matthias Geier <notifications@github.com> schrieb am Sa., 28. Juli 2018,
16:25:

**Comment by mgeier** [comment]
The current `master` version now does line-wrapping in the LaTeX output.
