### ISSUE TITLE
converted notebook contains a part of raw notebook

### ISSUE THREAD

**Issue by abchenson** [spatialaudio/nbsphinx#183]
I converted the attached notebook as part of a sphinx build and got the attached html.  As you can see there is a problem: the end of the html has a load of raw stuff from the nb printed out.

When I created the notebook, ran it and saved it I did not see this problem.  Then I shut the notebook, reloaded it, ran it and saved again.  At that point the error appeared.  The part of the notebook at which the raw stuff begins starts after the string "Export to plot.ly" and around that point tere are a lot of escaped "s.  But that is as far as I got diagnosing the problem.

nbsphinx (0.3.1)
nbconvert (5.3.1)
Sphinx (1.7.0)

[reproduce_nbconvert_bug.zip](https://github.com/spatialaudio/nbsphinx/files/1932274/reproduce_nbconvert_bug.zip)

**Comment by mgeier** [comment]
What happens if you use `nbconvert` to convert your notebook to HTML?

**Comment by abchenson** [comment]
Yes the problem exists there, I'll raise an issue with them.

[reproduce_plotly_err.html.zip](https://github.com/spatialaudio/nbsphinx/files/1946201/reproduce_plotly_err.html.zip)

**Comment by mgeier** [comment]
For reference, this is the issue created by @abchenson: https://github.com/jupyter/nbconvert/issues/802.

**Comment by mgeier** [comment]
Alternatively, this should be fixed by #611.
