### ISSUE TITLE
Sphinx documentation build fails with TypeError

### ISSUE THREAD

**Issue by csadorf** [spatialaudio/nbsphinx#187]
I have been using the nbsphinx extension for quite a while now to build documentation for a Python package on readthedocs.

Very recently builds started to fail with the following error:

```
TypeError: the JSON object must be str, not 'StringList'

Exception occurred:
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'StringList'
```

The full traceback and all other relevant information can be found [here](https://readthedocs.org/projects/signac/builds/7242036/).

I have not changed any relevant source code since the last successful build.

**Comment by mgeier** [comment]
Hmmm, this is quite strange.

I assume it works fine when you create your docs locally?

Probably we can find out what's going wrong if we find out how this `StringList` looks like.

Can you make an experimental branch of your repository and add the following to your `conf.py`?

```python
import nbsphinx

def fake_parse(self, inputstring, document):
    print('inputstring for', document.settings.env.docname)
    print(inputstring)

nbsphinx.NotebookParser.parse = fake_parse
```

When you run this branch on readthedocs, we can hopefully see in the logs how this mysterious `StringList` looks like ...

**Comment by csadorf** [comment]
@mgeier I added the above snippet to my `conf.py`, this is the result:

https://readthedocs.org/projects/signac/builds/7276519/

The privacy level for this branch is 'protected', because of that I also attached the log as text file, in case that you can't open it.
[7276519.txt](https://github.com/spatialaudio/nbsphinx/files/2059877/7276519.txt)

**Comment by rddaz2013** [comment]
mhh uft/json ..are you building on windows env?

https://bitbucket.org/glotzer/signac/src/8703eb992d3ff0741a8976b90fdda875b3cb460c/doc/signac_105_Command_Line_Interface.ipynb?at=master&fileviewer=file-view-default

some chars Line 151 ? breaks the json templating..
for a test only one ipynb at the time to the  readthedocs.

**Comment by csadorf** [comment]
@rddaz2013 I don't know what systems readthedocs uses to build the documentation.

I've run two additional tests with only one noteobok enabled:

1. Mock parsing disabled: https://readthedocs.org/projects/signac/builds/7281159/ [7281159.txt](https://github.com/spatialaudio/nbsphinx/files/2063503/7281159.txt)

2. Mock parsing enabled: https://readthedocs.org/projects/signac/builds/7281172/  [7281172.txt](https://github.com/spatialaudio/nbsphinx/files/2063502/7281172.txt)

I want to reemphasize that I built the exact same docs (and notebooks) on reathedocs without any issue many times before this problem first occurred, so I would be surprised if the fact that some of them contain UTF-8 chars has anything to do with this. Unless nbsphinx is not handling unicode correctly anymore or readthedocs switched to a different OS. On the other hand, I'm building with cPython3 so that would be surprising either way.

**Comment by rddaz2013** [comment]
thats like #127 / #247
thats not the json error "with the TypeError: the JSON object must be str, not 'StringList'."?

you are using nbsphinx==0.2.11 ?? (see  7281172.txt Line 200)  from 19 Nov 2016
install the github version!

**Comment by csadorf** [comment]
@rddaz2013 Thank you for noticing that! I did not realize that I had fixed the nbsphinx version in the doc/requirements.txt. I can only assume that I had some regression issue in the past or should have used `>=` instead of `==`.

I am now specifiying `nbsphinx>=0.3` which solves the issue. For the record, the default version installed within the readthedocs build environment is **not** sufficient.
