### ISSUE TITLE
Error in "nbinput" directive: maximum 1 argument(s) allowed, 4 supplied.

### ISSUE THREAD

**Issue by GreatYYX** [spatialaudio/nbsphinx#203]
I was struggling with a weird bug, the notebook that I wrote is here: https://github.com/usc-isi-i2/rltk/blob/master/docs/step_by_step.ipynb

There is a markdown cell where I put something like

```
Notes:

- `cached_property` is set for pre-computing. It's recommended to use if the property generating is time consuming.
- If you are using persistent Adapter (Redis, HBase) in Dataset, you can reuse it by calling `rltk.Dataset(adapter=...)` without other parameters.
```

This could be rendered to html correctly.

But if I changed it to:

```
> Notes:
> 
> - `cached_property` is set for pre-computing. It's recommended to use if the property generating is time consuming.
> - If you are using persistent Adapter (Redis, HBase) in Dataset, you can reuse it by calling `rltk.Dataset(adapter=...)` without other parameters.
```

I got an error (though it worked in Jupyter notebook):

```
/MY/LOCAL/PATH/step_by_step.ipynb:951: ERROR: Error in "nbinput" directive:
maximum 1 argument(s) allowed, 4 supplied.

.. nbinput:: ipython3
    :execution-count: 22
    :no-output:

    ds_abt = rltk.Dataset(reader=rltk.CSVReader(open('datasets/Abt-Buy/Abt.csv', encoding='latin-1')),
                       record_class=AbtRecord, adapter=rltk.MemoryAdapter())

    ds_buy = rltk.Dataset(reader=rltk.CSVReader(open('datasets/Abt-Buy/Buy.csv', encoding='latin-1')),
                       record_class=BuyRecord, adapter=rltk.MemoryAdapter())




   Notes:

   -  ``cached_property`` is set for pre-computing. It’s recommended to
      use if the property generating is time consuming.
   -  If you are using persistent Adapter (Redis, HBase) in Dataset, you
      can reuse it by calling ``rltk.Dataset(adapter=...)`` without
      other parameters.
```

I tried to write the the same thing in another markdown cell and the problem was not there anymore. Is it because the code cell above?

**Comment by mgeier** [comment]
Thanks, you found an interesting bug here!

This happens when a code cell is immediately followed by a block quote.

I will have to insert something into the auto-generated reST document, I'll have to look into that.

**Comment by mgeier** [comment]
I've created #205 to hopefully fix this. Can you please check if it works for you?

**Comment by GreatYYX** [comment]
👍 @mgeier Thanks for quick rely and fix. I tested on my local, it worked perfect. When will it be merged into master?

**Comment by mgeier** [comment]
Now!

**Comment by mgeier** [comment]
I've created #216 which reverts #205, but it should also solve the issue here.

The reason is that there is a more general problem, not only related to code cells. It also happens if a block quote follows an `image` directive or in fact any reST directive.

@GreatYYX Can you please check if #216 would still work for you?
