### ISSUE TITLE
skip checkpoint files

### ISSUE THREAD

**Issue by nlgranger** [spatialaudio/nbsphinx#204]
Hi, thank for this nice library!

Currently, sphinx passes checkpoint files as well as the actual notebooks to the parser. This adds useless parsing on these files and causes confusion because of redundant section references and unused files.

Would it be possible to detect and skip these?

**Comment by mgeier** [comment]
The usual way to avoid this is:

```python
exclude_patterns = ['**.ipynb_checkpoints']
```

See https://nbsphinx.readthedocs.io/en/0.3.4/usage.html#Sphinx-Setup

Does this work for you?

**Comment by nlgranger** [comment]
My bad I skipped over that part... thanks.

**Comment by nlgranger** [comment]
Closing.
