### ISSUE TITLE
Base-64 encoded images are not converted

### ISSUE THREAD

**Issue by seidlr** [spatialaudio/nbsphinx#214]
When I copy&paste images in a jupyter notebook they are saved as a base-64 encoded string as a cell attachment. But when I run nbsphinx on the notebook these images are not converted and not shown in the output. 
In a jupyter notebook I can solve this problem by downloading the notebook with "HTML Embedded" using jupyter notebook extensions. Here a custom nbconvert Exporter which correctly handles the embedded images is used. [Here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py) is the implementation from nbextensions derived from `nbconvert.HTMLExporter`.

I've recognized that you use a custom Exporter derived from `nbconvert.RSTExporter` to convert to RST. Is it possible to combine both Exporters to solve this issue?

**Comment by mgeier** [comment]
I don't know, why don't you give it a try!

See also #114.

**Comment by mgeier** [comment]
Thanks! It would be good if we could somehow process it cell-by-cell. This would avoid the first problem. Even if this is changed in https://github.com/jupyter/notebook/pull/3821, a user could still manually use the same name multiple times in a notebook.

**Comment by mgeier** [comment]
I've tried to come up with a cell-by-cell solution in #114.

What do you think about it?

**Comment by seidlr** [comment]
Great, I like it! 👍

**Comment by mgeier** [comment]
I've just merged #114.
