### ISSUE TITLE
Wrong size figures when using ipython retina figure_format

### ISSUE THREAD

**Issue by llambourne** [spatialaudio/nbsphinx#226]
Hi,

I just discovered this great extension, which has been really helpful to me. Thanks!

In order to make inline png figures from matplotlib display with 2x resolution I use the magic command: `%config InlineBackend.figure_format = 'retina'`. But the html output generated by nbsphinx displays the figure as twice the size with the same resolution, rather than the same size, with twice the resolution. 

Best,
Luke

**Comment by mgeier** [comment]
Thanks for reporting this!

I don't have a HiDPI screen so I've never tried this. I wonder why nobody has complained earlier.

I think this is merely a matter of reading and applying the cell output metadata, see #21.

I can probably take care of this while I'm working on #222, which is kinda related.

**Comment by mgeier** [comment]
BTW, did you try `'svg'` as figure format? This might look even better ...

**Comment by mgeier** [comment]
@llambourne I've added a commit to #222 that should take care of the "retina" image sizes. Can you please check if it works for you?

**Comment by llambourne** [comment]
In the end, I did switch to `'svg'` as a fix and you're right that they look even better (an example result is [here](https://ccsb-dfci.github.io/ccsblib/_build/html/validation_plots.html)).

I checked the fix you added to the `latex-image-size` branch and it works for me. Using `retina` format the figures are now the correct size and with the increased resolution. 

Thanks!

**Comment by mgeier** [comment]
You are welcome, thanks for testing!

I've seen that you are using an HTML table (Pandas dataframe) on that page, could you please check if #228 works for you?

**Comment by mgeier** [comment]
@llambourne, thanks for checking, and good catch!

The text-alignment rule was interfered with by the Sphinx CSS. I've made the rule more specific, now it seems to work as intended: https://github.com/spatialaudio/nbsphinx/pull/228/commits/bfc07ad4f97fcddb1db46208d06f8bcfc7966d2b
