### ISSUE TITLE
NoSuchKernel error

### ISSUE THREAD

**Issue by jhconning** [spatialaudio/nbsphinx#23]
After running smoothly for many builds, my readthedocs build is failing with this error. All I did was add a few more notebooks (which I later removed).  Could it be that nbphinx is no longer able to find and run a kernel it needs?

Here is more detail on the failing build
http://readthedocs.org/projects/dev-ii-seminar/builds/3700606/

and the exception listed there:
```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/dev-ii-seminar/envs/latest/local/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 143, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
NoSuchKernel
The full traceback has been saved in /tmp/sphinx-err-fz0JLj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mgeier** [comment]
This looks very similar: https://github.com/rtfd/readthedocs.org/issues/1827

From your exception it looks like you are using Python 2.7 on readthedocs and your notebooks seem to use Python 3.

See Point 4 there: http://nbsphinx.readthedocs.org/en/0.2.3/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org

**Comment by jhconning** [comment]
Thank you.  Yes, that was the problem.  To fix it ust involved going to readthedocs Admin, advanced settings and choosing Cpython 3.x as python interpreter (it had defaulted to 2.x)
