### ISSUE TITLE
Pandoc problems

### ISSUE THREAD

**Issue by JurajMa** [spatialaudio/nbsphinx#239]
I have installed the latest version of pandoc, yet I cannot use nbsphinx.
The error I get:

```Notebook error:
PandocMissing in test.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html
```

**Comment by JurajMa** [comment]
Solved.
This was not an nbsphinx issue, as expected, I am sorry...
Pandocs on Windows in combination with integrated IDEs and virtual environments seems to be a nasty package.

**Comment by tostenzel** [comment]
Hey @JurajMa , may I asked how you solved the problem - if you remember?

**Comment by JurajMa** [comment]
I don't remember. I might have installed it on my Windows machine, as opposed to in a virtual environent that I was using. Something like that.
