### ISSUE TITLE
Buggy white spaces and line breaks in markdown tables

### ISSUE THREAD

**Issue by falexwolf** [spatialaudio/nbsphinx#240]
Hi, thank you for the great package!

The following simple table

test1 | test2
----- | ------
word | many words in a row, long_words_here_to_which_break_up_in_several_pieces

renders as this:

![image](https://user-images.githubusercontent.com/16916678/48581787-c635a680-e8f0-11e8-851b-fc836acf1e84.png)

Any help is appreciated!

**Comment by mgeier** [comment]
Thanks for the report!

I cannot reproduce the problem, though.

Can you please provide some information about your system and how you installed `nbsphinx` and, more importantly, how you installed `pandoc` and which version of `pandoc` you are using?

**Comment by rddaz2013** [comment]
Yes i have the same problem - but not in all tables and more in the latex-output.
I look into it.

Please @falexwolf show us the  rst or html code of the table.

**Comment by mgeier** [comment]
@rddaz2013 

> can we fetch the rst output from nbsphinx before sphinx gets the table

Yes, you can use the `save-rst` branch for debugging, see https://github.com/spatialaudio/nbsphinx/tree/save-rst.

**Comment by rddaz2013** [comment]
i think https://github.com/jgm/pandoc/issues/3276 got it right.

The width header of the header breaks the line...if the text in die cell is much bigger. 
I test the workaround with the --columns=500 into the pandoc comandline
