### ISSUE TITLE
readthe docs github link is 404

### ISSUE THREAD

**Issue by aebrahim** [spatialaudio/nbsphinx#26]
For example, on the page http://nbsphinx.readthedocs.org/en/0.2.4/pre-executed.html

![image](https://cloud.githubusercontent.com/assets/1380168/13232562/8d9ad7c6-d964-11e5-8433-d550d15bd84b.png)

The "Edit on Github" link points to https://github.com/spatialaudio/nbsphinx/blob/0.2.4/doc/pre-executed.rst which gives a 404 (it should be linking to ipynb). I have no idea how to fix this, otherwise I would submit a PR.

**Comment by mgeier** [comment]
Thanks for the report!
This will be fixed in Sphinx version 1.3.6 (which will be released in about a week) and will hopefully soon after that be available on readthedocs.

See https://github.com/rtfd/readthedocs.org/issues/1871 and https://github.com/sphinx-doc/sphinx/issues/2278.

**Comment by aebrahim** [comment]
Haha you had already caught it!

**Comment by mgeier** [comment]
We should keep this open until it actually works, in case somebody else stumbles upon this bug.

**Comment by mgeier** [comment]
It should work now with Sphinx version 1.3.6, but RTD still doesn't use that by default (https://github.com/rtfd/readthedocs.org/issues/1871).

You can use this in your `requirements.txt`, though:

    sphinx>=1.3.6

**Comment by mgeier** [comment]
A newer version of Sphinx seems to be installed now, at least on Python 3: http://packages.readthedocs.io/en/latest/python/python3/

It probably still doesn't work for Python 2.

And it still doesn't seem to work when using `conda` (even with Python 3).

**Comment by mgeier** [comment]
This seems to work fine now.
