### ISSUE TITLE
0.4.0 pip install problem 

### ISSUE THREAD

**Issue by kmuehlbauer** [spatialaudio/nbsphinx#263]
While trying to package nbsphinx 0.4.0 for conda-forge (https://github.com/conda-forge/nbsphinx-feedstock/pull/12) we get an strange error importing `nbsphinx`.

```
import: 'nbsphinx'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/nbsphinx_1544793376612/test_tmp/run_test.py", line 2, in <module>
    import nbsphinx
  File "/home/conda/feedstock_root/build_artifacts/nbsphinx_1544793376612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/site-packages/nbsphinx.py", line 1492, in <module>
    sphinx.transforms.post_transforms.images.BaseImageConverter):
AttributeError: module 'sphinx' has no attribute 'transforms'
```

I could reproduce this locally in a fresh conda-environment:

```
conda create -n nbsphinx python=3.7 pip sphinx nbconvert!=5.4 docutils jinja2 traitlets nbformat
```

and pip installing nbsphinx:

```
>>> import nbsphinx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/miniconda3/envs/nbsphinx/lib/python3.7/site-packages/nbsphinx.py", line 1492, in <module>
    sphinx.transforms.post_transforms.images.BaseImageConverter):
AttributeError: module 'sphinx' has no attribute 'transforms'
```

Downgrading nbsphinx to 0.3.5 resolves the issue. Same behaviour in a fresh python 3.6 envoriment.

Any idea what's going on?

**Comment by kmuehlbauer** [comment]
Something isn't importing correctly.

If the import ```import sphinx.transforms.post_transforms.images``` is added, everything works correctly.

**Comment by mgeier** [comment]
Thanks for the report, and thanks for taking care of the `conda-forge` package!

I've had a similar problem before ...

Apparently Sphinx doesn't import an extension in the traditional way, so this problem doesn't occur when just running Sphinx.

This only occurs when importing with `import nbsphinx`, which is normally not necessary, but it is of course not forbidden.

I've created #264, which should fix the issue, as you mentioned above.

However, I'm wondering: Why do you need to `import nbsphinx` in order to create a package?

**Comment by kmuehlbauer** [comment]
@mgeier Thanks for looking into this.

The import happens in the test stage as a sanity check that the package was built correctly. This is by no means a thorough test but tells us that the package can at least be imported.

**Comment by kmuehlbauer** [comment]
@mgeier I've added a patch for the conda-forge build. It should be available already.

From my side the issue can be closed.

**Comment by mgeier** [comment]
Great, thanks!
