### ISSUE TITLE
KeyError: 'latex_elements'

### ISSUE THREAD

**Issue by goerz** [spatialaudio/nbsphinx#266]
It seems that yesterday's 0.4.0 release broke something:

https://readthedocs.org/projects/krotov/builds/8281165/

**Comment by mgeier** [comment]
Thanks for the report, and sorry for the inconvenience. I should have been more careful with this.

I've created #267 which hopefully fixes it.

I will make a bugfix release soon (probably tomorrow), but in the meantime you can just define this in your `conf.py` as a work-around:

    latex_elements = {}

**Comment by goerz** [comment]
Don’t worry about it! Things happen. Thanks for the quick response. 

nbsphinx is an amazing piece of software!

**Comment by falexwolf** [comment]
Thank you for the fix! Awesome!

**Comment by mgeier** [comment]
OK, I've just released version 0.4.1, I hope everything works now!
