### ISSUE TITLE
Syntax highlighting of python 2 notebooks not working on readthedocs

### ISSUE THREAD

**Issue by aebrahim** [spatialaudio/nbsphinx#27]
I'm not sure if this is the appropriate place for this, so feel free to close if it's not.

On readthedocs, I don't get syntax highlighting ([conf file](https://github.com/aebrahim/cobrapy/blob/nbsphinx/documentation_builder/conf.py)): http://cobrapy-test.readthedocs.org/en/latest/getting_started.html#Reactions

![image](https://cloud.githubusercontent.com/assets/1380168/13297232/24e997a2-dae6-11e5-961a-e39dd35cf0fb.png)

However, I do get syntax highlighting when I make the docs locally

![image](https://cloud.githubusercontent.com/assets/1380168/13297143/aaa70128-dae5-11e5-8ace-6c4e0a816028.png)

**Comment by mgeier** [comment]
I'm not sure what's the problem, because it works fine on the `nbsphinx` pages: http://nbsphinx.readthedocs.org/en/latest/code-cells.html.

You could try to add `Pygments` as a dependency to your `requirements.txt`.
Or probably it's just enough to "wipe" your build on RTD and re-build it again?

**Comment by aebrahim** [comment]
I figured it out. For some reason this bug affects notebooks run in python 2. The notebook needs to have ```"pygments_lexer": "ipython3"``` instead of ```ipython2````

I am changing the issue title to reflect this.

**Comment by mgeier** [comment]
Thanks for the update, I'm glad that it works now for you.

But I still don't know what the actual problem was ...
In your original example you are already using Python 3, but according to your screenshots this didn't work!
So why would it work now?

Did you happen to change the setting for the Python interpreter (2.x vs. 3.x) in the "Advanced Settings" on RTD (see point 4 [here](http://nbsphinx.readthedocs.org/en/latest/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org))?

Did you use or are you using `'IPython.sphinxext.ipython_console_highlighting'` in `extensions` in your `conf.py` (see #24)?

**Comment by marius311** [comment]
I had the same issue as OP, syntax highlighting inside notebook cells OK on a local build, but not on RTFD. I fixed it by following the instructions in @mgeier's link, mainly adding `IPython.sphinxext.ipython_console_highlighting` to my `extensions` in `conf.py` (I also had to add `ipython` to `requirements.txt`).

I guess its unclear to me from the link if I'm supposed to have had to do this, but at least I can say that it worked. 

Repo in question, if its useful to anyone: http://cosmoslik.readthedocs.io/

**Comment by mgeier** [comment]
I think it should not be necessary to explicitly specify `IPython.sphinxext.ipython_console_highlighting`.
If everything works as intended, the lexer should be registered automagically when installing the IPython package.

@marius311 Probably just adding `ipython` to `requirements.txt` is enough?

**Comment by marius311** [comment]
Just checked and you're right, just `ipython` did it. Thanks.

**Comment by mgeier** [comment]
Thanks for confirming that! I've added some documentation about it: http://nbsphinx.readthedocs.io/en/latest/usage.html#Syntax-Highlighting

**Comment by mgeier** [comment]
See https://github.com/ContinuumIO/anaconda-issues/issues/1430
