### ISSUE TITLE
Notebook title disappears from content list in any page but index

### ISSUE THREAD

**Issue by robertorolo** [spatialaudio/nbsphinx#273]
I added a notebook to my index.rst. The title and sections appears in my contents list, i am using sphinx_rtd_theme, but only when i am on index page, when i navigate to other pages the notebook title disappears from the contents list.

**Comment by mgeier** [comment]
Did you re-build all pages?

If not, please try either using the `-E` flag or deleting the build directory before re-building.

**Comment by robertorolo** [comment]
I was able to fix it by changing `'collapse_navigation': False,` on conf.py  theme options  from True to False.

**Comment by mgeier** [comment]
Thanks for the update.

Please note that your specific change is not actually the immediate reason why it works now. Changing *anything related to HTML output* in `conf.py` will lead Sphinx to re-build all HTML pages, which is the actual reason why now all your pages are correct.

You don't have to use this specific option (but I personally like this option, so I recommend to keep it anyway).

I guess I can close this issue now.
