### ISSUE TITLE
larger images break LaTeX PDF generation

### ISSUE THREAD

**Issue by madmott** [spatialaudio/nbsphinx#276]
A reproducing example can be found at https://github.com/datarobot/nbsphinx-minimal-repro (pared down from my project's normal build process - there's some vestiges that amount to "this is here because it's needed in the full version", my apologies).

When I use nbsphinx==0.3.5, everything builds correctly.  When I use nbsphinx==0.4.0 or nbsphinx==0.4.1 I get the normal PDF up until the image, followed by about 5000 blank pages instead of the image, and then the build process errors.

Logs from the end of the build process:
```
Underfull \vbox (badness 10000) detected at line 257
! TeX capacity exceeded, sorry [parameter stack size=10000].
\__prop_split_aux:w ... #2#3\q_mark #4#5\q_stop ->
                                                  #4{\tl_set:Nn \l__xeCJK_fo...
l.257 \end{nbsphinxfancyoutput}
```

The specific problematic section in the generated .tex file seems to be
```
\begin{nbsphinxfancyoutput}

\noindent\sphinxincludegraphics[width=715\sphinxpxdimen,height=852\sphinxpxdimen]{{examples_advanced_model_insights_Advanced_Model_Insights_3_1}.png}

\end{nbsphinxfancyoutput}
```
When I modify the .tex file replace it with the following, the build works again.
```
\begin{nbsphinxfancyoutput}

\noindent\sphinxincludegraphics{{examples_advanced_model_insights_Advanced_Model_Insights_3_1}.png}

\end{nbsphinxfancyoutput}
```

This may be related to https://github.com/spatialaudio/nbsphinx/pull/222 and related work with images.

For now I'm simply downgrading as a workaround.

**Comment by madmott** [comment]
This may actually be a duplicate of https://github.com/spatialaudio/nbsphinx/issues/231 - I'm not entirely sure.

**Comment by mgeier** [comment]
Thanks for the report!

Yes, this is related to #222 and #231, but I didn't think the error would be that bad.

Sadly, I don't really know a solution to this.

The `\sphinxincludegraphics` macro actually is able to shrink big images to fit on the page, but this only works if `width` and `height` are not given.

Probably @jfbu has an idea?

**Comment by mgeier** [comment]
@madmott A possible work-around would be to use PDF plots, did you try that yet?
See https://nbsphinx.readthedocs.io/en/0.4.1/code-cells.html#Plots.

**Comment by jfbu** [comment]
I will give a look: I don't see what's a priori bad in the ``[width=715\sphinxpxdimen,height=852\sphinxpxdimen]`` options, so this is intriguing. (I am busy at this time so this may have to wait for the week-end, if issue not solved until then)

**Comment by jfbu** [comment]
This is a pure LaTeX problem which I can reproduce with this example

```latex
\documentclass{article}

\usepackage{framed}
\usepackage{graphicx}

\begin{document}
\begin{framed}
  \includegraphics[height=35cm]{example-image-a}
\end{framed}
\end{document}
```

the image does not fit on the page and this leads `framed.sty` into infinite loop (or something like this; I am bit tired and can't investigate more now.

Sphinx could possibly make `\sphinxincludegraphics` check that the height is not too big, the problem is perhaps the problem is worse if the framed image inclusion is suppose to take place near bottom of page. The problem could arise in pure Sphinx as some other things not only Verbatim are also rendered via framed.sty and may have an image inclusion. Solution will perhaps not be easy.

**Comment by madmott** [comment]
thanks for the tip re: xelatex usage.  That should help us out.

**Comment by jfbu** [comment]
Well, we were more intelligent in pre-fora era, thinking out things by ourselves, and during the process of posting my LaTeX question on tex.sx I realized that the only matter here is to make sure `framed` environment will have enough room to fit picture on one page (if it is too big for current page, of course it will try on next one). 

(I had somehow focused on some manoeuvers to split the image across pages)

`\textheight` gives an idea of the maximal height but `framed` needs a bit more space than actual height of included graphics, an idea of a fix could be to use a custom `\nbsphinxincludegraphics` which will never allow height larger than say `\textheight - something` where the something could be `20pt` probably enough. The `keepaspectratio` key of `\includegraphics` is handy here, allowing a cap on `height` while no need to adjust our setting for `width`.

**Comment by jfbu** [comment]
@madmott I forgot to say that if you switch to more normal usage of `xelatex` you will want not to set `'utf8extra'` key to empty.

Going back to main issue, your minimal example compiles succesfully with #277 in my testing... (which I did by commenting out `xeCJK` as I don't have the fonts it wants with `xelatex`).
