### ISSUE TITLE
How to skip some cells?

### ISSUE THREAD

**Issue by wookayin** [spatialaudio/nbsphinx#285]
This is really a great plugin for sphinx!

I am curious how we can skip some cells from ipython notebooks that we mark using some comments, directives, or [cell metadata](https://medium.com/@mjspeck/presenting-code-using-jupyter-notebook-slides-a8a3c3b59d67) to be excluded in converting. This would be super useful in writing documentations when we want to exclude some preambles or dirty data preparation codes from the rendered sphinx docs.

I don't think ipython nbconvert does have this feature :)

**Comment by mgeier** [comment]
Thanks!

Is https://nbsphinx.readthedocs.io/en/0.4.2/hidden-cells.html what you need?

> when we want to exclude some preambles or dirty data preparation codes

Well it would probably be better to clean up the preparation code, wouldn't it?

And did you consider moving the (clean) preparation code to a separate `.py` file and then using `import` to work with it in your notebook?

> I don't think ipython nbconvert does have this feature :)

In fact, there are multiple ways to do this in `nbconvert`:

By regex with https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#nbconvert.preprocessors.RegexRemovePreprocessor

By tags with `TagRemovePreprocessor.remove_cell_tags` and `TagRemovePreprocessor.remove_input_tags` (see https://nbconvert.readthedocs.io/en/latest/config_options.html)

**Comment by wookayin** [comment]
This works so great, sorry for missing that!

**Comment by ratnanil** [comment]
I'd be very interested to use nbconvert.preprocessors.RegexRemovePreprocessor. Can this funcionality be used within nbsphinx? I cant find anything in the docs..

**Comment by ratnanil** [comment]
It seems that `nbconvert.preprocessors.RegexRemovePreprocessor` [is disabled](https://github.com/spatialaudio/nbsphinx/blob/880bf3a30dff75e16a2b1644e8293e13524a5af0/src/nbsphinx.py#L722-L726) (see also https://github.com/spatialaudio/nbsphinx/issues/305#issuecomment-505484450). Does this mean that I cannot use `RegexRemovePreprocessor`?

**Comment by mgeier** [comment]
@ratnanil See my answer at https://github.com/spatialaudio/nbsphinx/issues/341#issuecomment-544119378.
