### ISSUE TITLE
Recreating nbsphinx's Info/Warning Boxes in .rst

### ISSUE THREAD

**Issue by rsokl** [spatialaudio/nbsphinx#286]
Hi @mgeier , hope all is well. 

I am converting many of my notebooks to .rst files, and am struggling to reproduce the same kinds of colored boxes that were being produced by nbsphinx.

For example, a notebook markdown cell containing the following: 

```
<div class="alert alert-info"> 

**Definition**: 

In the context of high-level languages like Python, Matlab, and R, the term **vectorization** describes the use of optimized, pre-compiled code written in a low-level language (e.g. C) to perform mathematical operations over a sequence of data. This is done in place of an explicit iteration written in the native language code (e.g. a "for-loop" written in Python). 

</div>
```
renders nicely as:

![image](https://user-images.githubusercontent.com/29104956/52894235-4aa7f780-3174-11e9-870d-14ba54178a56.png)

My understanding is that you had to roll your support for this. So I am wondering - can this be reproduced via sphinx from a .rst file? I attempted putting the same html in a `.. raw:: html` block, but to no avail. How do you handle these?

Thank you!

**Comment by mgeier** [comment]
Yes, those are made with the custom Sphinx directives `nbinfo` and `nbwarning`: https://nbsphinx.readthedocs.io/en/0.4.2/a-normal-rst-file.html#sphinx-directives-for-info-warning-boxes

**Comment by rsokl** [comment]
Thanks for pointing those out (and for writing them)!

**Comment by rsokl** [comment]
Thank you for adding `nbsphinx_custom_formats` in 0.4 @mgeier . Combining `nbsphinx` with `jupytext` is **such** a killer combo. I figured this wasn't issue-worthy, but I wanted to show my appreciation. Awesome add-on!

**Comment by mgeier** [comment]
Thanks @rsokl, it's always nice to hear such positive feedback!

I added `nbsphinx_custom_formats` to experiment with https://github.com/mgeier/jupyter-format/, but I guess the real-world usage will be mostly with `jupytext`, which is great!

**Comment by rsokl** [comment]
The two fit hand-in-hand since you automatically run cells that don't have outputs, which is the major limitation of `jupytext`!
