### ISSUE TITLE
Multiline equation no longer rendering after upgrade (pandoc 2.1 ->2.2)

### ISSUE THREAD

**Issue by rsokl** [spatialaudio/nbsphinx#287]
### Brief Summary
I began building my site from a fresh machine. In moving to a newer version of nbsphinx and its dependencies, my mulit-line latex equations broke.

I can confirm that downgrading `pandoc 2.2.3` down to `pandoc 2.1.3` **restores the proper behavior**.

### Example of What Broke
The following markdown cell:
```
\begin{equation}
\left(
\begin{array}{*{6}{X}}
  y[2] & y[4] & y[0] & y[4] & y[4] & y[4]
\end{array}
\right)
% 
\rightarrow
\left(
\begin{array}{*{6}{X}}
  -2 & -4 & 0 & -4 & -4 & -4
\end{array}
\right)
\end{equation}
```
**used to render, via nbsphinx, as:**
![image](https://user-images.githubusercontent.com/29104956/52894731-02410780-317d-11e9-9165-0a4048078d80.png)

**It now renders as:**

![image](https://user-images.githubusercontent.com/29104956/52894726-f1909180-317c-11e9-820b-699e88b29a5f.png)

### System Information
- OS: Windows
- Python 3.7
- nbsphinx 0.4.2
- sphinx 1.7.9
- pandoc 2.2.3
- nbconvert 5.3.1

As I mentioned above. Holding all of these things constant and downgrading pandoc to `2.1.3` resolves this issue. I tried `2.2.0` and it failed as well - it seems like the breaking change was introduced here.

**Comment by mgeier** [comment]
Thanks for the report!

I guess this is the same problem as #279, so the same work-around should work.

If you have an idea how to fix this properly, please let me know!

**Comment by rsokl** [comment]
I will look into this. Should I look into #257 to understand what code the solution should be touching?

**Comment by mgeier** [comment]
Yes, #257 is the culprit.

The problem is that `pandoc` changed its behavior regarding using `RawBlock` and `RawInline` at some point.

I was trying to find a way to handle both old and new `pandoc` versions, but obviously it didn't work that well.

I hope you have more success!

**Comment by rsokl** [comment]
I'm closing this, given that you raise a runtime warning for being on pandoc >= 2.0.

Hope all is well!
