### ISSUE TITLE
Support pandoc > 2.0.0

### ISSUE THREAD

**Issue by dmfigol** [spatialaudio/nbsphinx#290]
Currently ``nbsphinx`` complains with a warning about pandoc being version 2.0 or higher.
On macOS, you get only pandoc 2.2+ via Homebrew, on Debian you still get 1.x from the package manager, but it is easy to download the latest pandoc version as a single binary from their git: https://github.com/jgm/pandoc/releases
Is there any plan to add support for pandoc > 2.0.0?
Thanks!

**Comment by mgeier** [comment]
This warning actually comes from the `nbconvert` module.

I've asked about it in https://github.com/jupyter/nbconvert/issues/928

And there is a further issue and a PR:
* https://github.com/jupyter/nbconvert/issues/815
* https://github.com/jupyter/nbconvert/pull/933

Feel free to leave a comment there!

It looks like there is no progress in `nbconvert`, probably I'll have to avoid this warning from within `nbsphinx`.

**Comment by mgeier** [comment]
BTW, `pandoc` >= 2 is fully supported, this warning message can be ignored.

**Comment by dmfigol** [comment]
Thank you!

**Comment by aaronmarkham** [comment]
I was able to get this warning to go away by adding this to my environment.yml file - which I use with conda like `conda env update -f environment.yml`:
```
name: my-conda-env
dependencies:
  # this version is needed to make sure pip upgrades are actually run
  - conda>=4.6.13
  # other stuff... 
- pip:
  # using nbconvert master until v5.5 comes out
  - git+https://github.com/jupyter/nbconvert@master
  # other stuff...
```
When v5.5 lands, you can probably remove this nbconvert line/dependency.

**Comment by mgeier** [comment]
@aaronmarkham It looks like `nbconvert` was released just a few hours before your comment (also on `conda-forge`).

I guess this issue can be closed.

Please comment if there are still problems!
