### ISSUE TITLE
"NotImplementedError: Unknown node: pending_xref" error on Sphinx v1.8.4

### ISSUE THREAD

**Issue by Naereen** [spatialaudio/nbsphinx#293]
Hi,
I am using `nbsphinx` with latest version of `sphinx`, and I am encountering issues of `NotImplementedError: Unknown node: pending_xref` when using `nbsphinx` to read & parse & convert some `.ipynb` files in my Sphinx project.

I opened an issue on `sphinx-doc/sphinx` (https://github.com/sphinx-doc/sphinx/issues/6166), but @tk0miya told me that the bug is most likely coming from `nbsphinx` itself.
Apparently, a `pending_xref` is generated here:
https://github.com/spatialaudio/nbsphinx/blob/c43ae330f8d466fb3da90eee37f9e492ba17c33b/src/nbsphinx.py#L1353

Do you know why? Could it be removed?

I give more details on my bug and my project on [the issue on sphinx-doc/sphinx](https://github.com/sphinx-doc/sphinx/issues/6166#issue-419501493).

Thanks in advance, and of course I stay at your disposal if need more details.

**Comment by mgeier** [comment]
Thanks for the report!

Could you please create a minimal example project that shows the problem?
Ideally, this should only depend on `sphinx` and `nbsphinx`.

> Do you know why?

Yes. The `pending_xref` nodes are used to turn links to Sphinx source files into links to the generated HTML files, see https://nbsphinx.readthedocs.io/en/0.4.2/a-normal-rst-file.html#links-to-notebooks-and-other-sphinx-source-files

> Could it be removed?

Not without losing this functionality.

**Comment by Naereen** [comment]
Hi. Okay, thanks for the details!
I don't think I can quickly and easily do such minimal examples, I have a dozen of notebooks in my project, and apparently I cannot know which one created an error (from the error log). Sorry :-(

**Comment by mgeier** [comment]
> I don't think I can quickly and easily do such minimal examples

OK, no problem, but then I also can't help you. Sorry :-(

**Comment by Naereen** [comment]
That was a weird exchange...

Do you have any idea how I could nail down the problem and precisely identify which notebook file causes the issue?

**Comment by mgeier** [comment]
You can start removing notebooks as long as the error doesn't go away.
In the end you should have a single notebook.
Then you can start removing cells until you have a single cell.
Then start removing content from this cell.
Then you can remove stuff from your `conf.py`, etc.

In the end you should have a minimal example.

**Comment by Naereen** [comment]
Hi,
I'll do this as soon as I can. Thanks!

**Comment by Naereen** [comment]
Hi, I don't and will probably never have the time to try, sorry.
(just for curiosity, I tweaked my `conf.py` file in sphinx to not use the nbsphinx extension on ReadTheDocs, as I modified manually the code of my local sphinx package to fix this error but cannot modify the code used on ReadTheDocs servers, here is the file if you are curious of this specific line: https://github.com/SMPyBandits/SMPyBandits/blob/master/conf.py#L114)

**Comment by Borda** [comment]
I have a similar issue and in the end, my solution was to rename the notebook file, so there is no work "model", the original name was `notebooks/segment-2d_slic-fts-model-gc.ipynb`

**Comment by doutriaux1** [comment]
I have a similar issue it seems to be related to having a cell asking for a password:
```python
# Let's ask for the password and setup ssh agent
import getpass
password = getpass.getpass()+"\n"
```

**Comment by doutriaux1** [comment]
The above cell seems to lead to the following error:
```bash
Exception occurred:
  File "/g/g19/cdoutrix/miniconda3/envs/kosh/lib/python3.6/site-packages/sphinx/writers/html5.py", line 790, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: pending_xref
The full traceback has been saved in /tmp/sphinx-err-un1e9e6b.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mgeier** [comment]
@doutriaux1 Can you please provide a minimal reproducible example?

I've tried your code example above, and I'm getting a different error:

```
StdinNotImplementedError: getpass was called, but this frontend does not support input requests.
```

It's not surprising to me that this doesn't work.
How would you expect this to behave?
