### ISSUE TITLE
exclude_patterns overridden when nbsphinx_execute = 'always'

### ISSUE THREAD

**Issue by ajp619** [spatialaudio/nbsphinx#296]
I  found that if I set 
`nbsphinx_execute = 'always'` 
in conf.py that my notebooks in .ipynb_checkpoints are no longer ignored even though I have
`exclude_patterns = ['build', '**.ipynb_checkpoints']`

thanks for a great library!

**Comment by mgeier** [comment]
Thanks for the report!

I tried but I couldn't reproduce the problem.

Could you please provide a minimal example project that shows the problem?

**Comment by ajp619** [comment]
Ok, I think this reproduces the problem: https://github.com/ajp619/nbsphinx-test
Python 3.6.5
Dependencies captured with poetry
I modified the Makefile to use ipython because in my actual project I'm running some cell magics.
I get the following error when I run `make html` from the report directory:
```
nbsphinx_text/reports$ make html
export FORMAT_OVERRIDE=pandas; ipython -m sphinx "source" "build"
Running Sphinx v2.0.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
[TerminalIPythonApp] ERROR | Timeout waiting for execute reply (30s).

Notebook error:
TimeoutError in .ipynb_checkpoints/nbsphinx_test-checkpoint.ipynb:
Cell execution timed out
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
~/.pyenv/versions/3.6.5/lib/python3.6/runpy.py in run_module(mod_name, init_globals, run_name, alter_sys)
    203         run_name = mod_name
    204     if alter_sys:
--> 205         return _run_module_code(code, init_globals, run_name, mod_spec)
    206     else:
    207         # Leave the sys module alone

~/.pyenv/versions/3.6.5/lib/python3.6/runpy.py in _run_module_code(code, init_globals, mod_name, mod_spec, pkg_name, script_name)
     94         mod_globals = temp_module.module.__dict__
     95         _run_code(code, mod_globals, init_globals,
---> 96                   mod_name, mod_spec, pkg_name, script_name)
     97     # Copy the globals of the temporary module, as they
     98     # may be cleared when the temporary module goes away

~/.pyenv/versions/3.6.5/lib/python3.6/runpy.py in _run_code(code, run_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
     83                        __package__ = pkg_name,
     84                        __spec__ = mod_spec)
---> 85     exec(code, run_globals)
     86     return run_globals
     87

~/Library/Caches/pypoetry/virtualenvs/nbsphinx-test-py3.6/lib/python3.6/site-packages/sphinx/__main__.py in <module>
     13 from sphinx.cmd.build import main
     14
---> 15 sys.exit(main(sys.argv[1:]))

SystemExit: 2
/Users/ap186098/Library/Caches/pypoetry/virtualenvs/nbsphinx-test-py3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2819: UserWarning: Unknown failure executing module: <sphinx>
  warn('Unknown failure executing module: <%s>' % mod_name)
```
My actual issue is caused by the absence of a credentials file, so I'm mimicking it by causing a timeout when the file isn't present.

Hope that all makes sense!

**Comment by mgeier** [comment]
Thanks for the example project!

I do get an error when running `make html`, but it's a different one:

    NameError: name 'os' is not defined

When I comment out `nbsphinx_execute = 'always'`, I don't get this error. This is because the notebook is not executed by default because it contains some `execution_count` values and it's therefore not considered to be "without outputs".

However, the `exclude_patterns` still don't work as expected, as shown by this warning message:

    [...]/nbsphinx-test/reports/source/.ipynb_checkpoints/nbsphinx_test-checkpoint.ipynb: WARNING: document isn't included in any toctree

Then I found the problem in your `conf.py`: you are overwriting `exclude_patterns` with an empty list, therefore the previously defined patterns are not used:

https://github.com/ajp619/nbsphinx-test/blob/cafb0c3ef8f4f42f040e729560dfc6df161de9ea/reports/source/conf.py#L47

**Comment by ajp619** [comment]
Thanks for the response. That was indeed the problem. I really should have caught that. =-)
