### ISSUE TITLE
Doesn't have a title: no link will be generated

### ISSUE THREAD

**Issue by jetheurer** [spatialaudio/nbsphinx#310]
I have an issue where the following warning comes up:

```
WARNING: toctree contains reference to document 'example' that doesn't have a title: no link will be generated
```

Where example is the name of my notebook `example.ipynb`

and this is the command I run: `python3 -m sphinx -b html -j 4 docs/source/ $BUILD`

When looking at the generated files, I dont get the link to example in my documentation.

My toctree looks like this:

```rst
.. toctree::
   :maxdepth: 2
   :caption: Contents:

   example.ipynb
   readme
   modules
```

To clarify, the html file: example.html builds, but the link in index.rst is dropped.

**Comment by jetheurer** [comment]
This seems related to: https://stackoverflow.com/questions/55297443/including-of-notebook-with-nbsphinx-fails

**Comment by jetheurer** [comment]
Here is a minimal example: [minimal_nbsphinx.zip](https://github.com/spatialaudio/nbsphinx/files/3463361/minimal_nbsphinx.zip)

Please run using `bash build.sh`

**Comment by jetheurer** [comment]
For those that run into this again,

Here is a minimal working notebook:

```json
{
 "cells": [
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "# Test"
    ]
   }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

The most relevant component being:
```json
    "source": [
     "# Test"
    ]
```
All notebooks need a markdown section with a title!

**Comment by TCACastelijns** [comment]
I know this issue is closed, but I get still get the error above. Even if my notebooks contains titles.

My index.rst contains of
```

- predict.ipynb
- train.ipynb
- evaluate.ipynb
```

I wrote documentation for predict step with markdown and code examples:

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Predict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# For running this notebook\n",
    "import sys\n",
    "sys.path.append('../..')\n",
    "\n",
    "# Standard\n",
    "from datetime import timedelta, datetime\n",
    "import pandas as pd\n",
    "import pytz\n",
    "import re\n",

```
.....
```
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```


The train and evaluate scripts only contains a title and one line of markdown.

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "bcf5baf7",
   "metadata": {},
   "source": [
    "# Evaluate"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4599130f",
   "metadata": {},
   "source": [
    "Evaluate's pipeline docs"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

If I build the documenation I get the following warnings:

`/docs/_src/index.rst:11: WARNING: toctree contains reference to document 'predict' that doesn't have a title: no link will be generated`

But the `train.ipynb` and `evaluate.ipynb` notebooks doesn't have any problems and are connected to the index. Anyone any idea how to solve this?

**Comment by mgeier** [comment]
@TCACastelijns Do you get any other warnings?

This sounds a bit like #549 which was fixed in #552 and released in `nbsphinx` version 0.8.3.

**Comment by TCACastelijns** [comment]
@mgeier : Thanks for this hint. Indeed I also got the long line warning:

```
/docs/_src/predict.ipynb:: WARNING: Line 810 exceeds the line-length-limit.
/docs/_src/predict.ipynb:: WARNING: Each notebook should have at least one section title
```

I upgraded to `nbsphinx` version 0.8.3 and that fixed the problem!

**Comment by theRealSuperMario** [comment]
For those who are still running into this, you also need to make sure that `.ipynb` is **not** added to the `source_suffix` list.

See here https://stackoverflow.com/a/70474616/10045897

**Comment by mgeier** [comment]
@pique-b Please note that the term "title" is ambiguous here.

It does *not* mean the `title` field in the Jupyter notebook metadata.

It means the title in the sense of "the first section title of the page".

The Pandoc error is unrelated, maybe you have to add it to the PATH?

Even if you have it installed, the Python installer might still not be able to find it.
