### ISSUE TITLE
nbsphinx doesn't load the css style of Jupyter cells

### ISSUE THREAD

**Issue by Trizali** [spatialaudio/nbsphinx#314]
Hi everyone!

I have a Jupyter notebook whose markdown cells have a CSS-style. This style is load and read from an external CSS file that I have stored in my local ('./style/common.css')

To do this, I include it in my Jupyter notebook by using a function:
```
import style
style.css_styling()
```
And I apply this style in the desired cells using 
`<div class = common></div>`

And this works perfectly.

**The problem is when** I generate the HTML in nbsphinx using the command 
`> make html`

because **it does NOT keep in the HTML built with nbsphinx the CSS contained in the markdown cells of the Jupyter notebook.**

How does it work in these cases?

Thank you in advance.

Greetings

**Comment by mgeier** [comment]
Thanks for the report!

Does it work when you use `nbconvert`?

Can you please provide an minimal example notebook and CSS file including a minimal Sphinx configuration that shows the problem?

**Comment by mgeier** [comment]
I'm closing this due to lack of response.
