### ISSUE TITLE
pdf / svg generation issue with new pandoc

### ISSUE THREAD

**Issue by LocutusOfBorg** [spatialaudio/nbsphinx#317]
Hello, (please ask for more information in case I missed anything).

With the new pandoc 2.5 and new ghc 8.6.5 / texlive in Debian unstable, we are hitting a test failure in pdf generation, because of "can't include svg file"

https://ci.debian.net/data/autopkgtest/unstable/amd64/n/nbsphinx/2916428/log.gz

```
! LaTeX Error: Unknown graphics extension: .svg.

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.292 ...54518f516c4c0bc19d1ae86e01/version}.svg}}
                                                  %^^M
? 
! Emergency stop.
 ...                                              
                                                  
l.292 ...54518f516c4c0bc19d1ae86e01/version}.svg}}
                                                  %^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on nbsphinx.log.
Latexmk: Index file 'nbsphinx.idx' was written
Latexmk: List of undefined refs and citations:
  Reference `a-normal-rst-file::doc' on page 1 undefined on input line 269
Latexmk: Summary of warnings from last run of (pdf)latex:
  Latex failed to resolve 1 reference(s)
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'nbsphinx.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
make: *** [Makefile:33: nbsphinx.pdf] Error 12
```

The run test is really simple, trying to build documentation
```
cp -prd README.rst doc $AUTOPKGTEST_TMP

cd $AUTOPKGTEST_TMP

python3 -m sphinx -b html doc doc-html

python3 -m sphinx -b latex doc doc-latex
make -C doc-latex all-pdf
```

**Comment by mgeier** [comment]
Are you sure this worked with older `pandoc` versions?

SVG images are simply not supported by LaTeX (or at least by `pdflatex`). But they can be converted automatically, see https://nbsphinx.readthedocs.io/en/0.4.2/markdown-cells.html#SVG-support-for-LaTeX.

**Comment by LocutusOfBorg** [comment]
This is an example of test with older pandoc...
https://ci.debian.net/data/autopkgtest/unstable/amd64/n/nbsphinx/2860536/log.gz

**Comment by LocutusOfBorg** [comment]
Don't ask me how, but it worked before...

**Comment by LocutusOfBorg** [comment]
I started from Debian testing, upgraded everything except pandoc

Output written on nbsphinx.pdf (41 pages, 487297 bytes).
Transcript written on nbsphinx.log.
=== TeX engine is 'pdfTeX'
Latexmk: Index file 'nbsphinx.idx' was written
Latexmk: Log file says output to 'nbsphinx.pdf'
Latexmk: All targets () are up-to-date
make: Leaving directory '/tmp/pippo/doc-latex'
root@Unimatrix05-Bionic:/nbsphinx-0.4.2+ds# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  liblua5.1-0
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  pandoc pandoc-data
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/16.1 MB of archives.
After this operation, 7874 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 51526 files and directories currently installed.)
Preparing to unpack .../pandoc_2.5-2_amd64.deb ...
Unpacking pandoc (2.5-2) over (2.2.1-3+b2) ...
Preparing to unpack .../pandoc-data_2.5-2_all.deb ...
Unpacking pandoc-data (2.5-2) over (2.2.1-3) ...
Setting up pandoc-data (2.5-2) ...
Setting up pandoc (2.5-2) ...
Processing triggers for man-db (2.8.7-3) ...
root@Unimatrix05-Bionic:/nbsphinx-0.4.2+ds# rm -rf /tmp/pippo/* && ./debian/tests/perform-doc 
Running Sphinx v1.8.5
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
[snip]
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxzplm.fd)<<omx.cmap>>
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1zplm.fd)

LaTeX Font Warning: Font shape `T1/lmtt/m/n' undefined
(Font)              using `T1/cmr/m/n' instead on input line 224.


LaTeX Font Warning: Font shape `TS1/lmtt/m/n' undefined
(Font)              using `TS1/cmr/m/n' instead
(Font)              for symbol `textquotesingle' on input line 1.


LaTeX Warning: Hyper reference `a-normal-rst-file::doc' on page 1 undefined on 
input line 269.


LaTeX Warning: Reference `a-normal-rst-file::doc' on page 1 undefined on input 
line 269.


! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.292 ...54518f516c4c0bc19d1ae86e01/version}.svg}}
                                                  %^^M
? 
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.292 ...54518f516c4c0bc19d1ae86e01/version}.svg}}
                                                  %^^M
? [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.314 ...a8456b3d03b8794cac/python:nbsphinx}.svg}}
```

**Comment by mgeier** [comment]
OK, I see that you are trying to build the PDF documentation of `nbsphinx` itself.

This hasn't worked for a long time, because the "badges" on the "Installation" page are (remote) SVG files.

Probably in earlier versions the error was somehow ignored, but I assume it was already there.

The solution would be to auto-convert SVG images to PDF.
I've tried this, but it doesn't work yet: #319

I think this is because auto-downloading SVGs and auto-converting them doesn't play well together, but I'm not sure.

If you have any further ideas, please let me know.

**Comment by LocutusOfBorg** [comment]
So, your suggestion is to just disable the above test, and live happy? because it is what I'm doing right now :) I don't think such configuration can be supported, and our builders can't download stuff from the internet.
If it was silently failing before, better disable it now

**Comment by mgeier** [comment]
> So, your suggestion is to just disable the above test, and live happy?

No, that wasn't my suggestion at all.
My suggestion was to fix the problem with something like #319, but I don't know yet how to make it work.

> our builders can't download stuff from the internet.

OK, then the build *should* arguably fail, because the documentation does contain a few images that are supposed to be downloaded from the internet.

> If it was silently failing before, better disable it now

It was failing before in the sense that there were some error messages in the LaTeX run, but a PDF file was created in the end. It just didn't have the SVG "badges" in it (see e.g. https://readthedocs.org/projects/nbsphinx/downloads/pdf/0.4.2/#subsection.1.1).

I do want to fix this, I just haven't found a solution yet.

But anyway, if there is no internet connection during LaTeX/PDF creation, this part of the tests should probably be disabled.

**Comment by mgeier** [comment]
So I looked into this a bit further, and found the culprit, see #319.

However, building the docs without internet connection still doesn't work (and I'm not planning to change that).

**Comment by LocutusOfBorg** [comment]
yes, I was wrong, when that testsuite runs, internet is enabled
(we have build process that has no internet, but this case is the autopkgtests, with full hw/internet access)

**Comment by mgeier** [comment]
OK, great, I've just merged #318, that means that `master` should now build without errors (assuming that you have `librsvg2-bin` installed, see https://nbsphinx.readthedocs.io/en/0.4.2/markdown-cells.html#SVG-support-for-LaTeX).

**Comment by LocutusOfBorg** [comment]
I think you mean #319 :)
anyhow, in order to use it, I have to package this one
https://github.com/sephalon/sphinxcontrib-svg2pdfconverter

**Comment by mgeier** [comment]
Yes indeed!

> anyhow, in order to use it, I have to package this one
https://github.com/sephalon/sphinxcontrib-svg2pdfconverter

Yes, is this a problem?

Or is there an alternative I should use?

**Comment by LocutusOfBorg** [comment]
No problem, I'll package it for Debian and Ubuntu and use it :)

**Comment by LocutusOfBorg** [comment]
Closing the issue in the meanwhile
