### ISSUE TITLE
GIF is missing

### ISSUE THREAD

**Issue by quasiben** [spatialaudio/nbsphinx#321]
I am trying to use `nbsphinx` with a notebook which contains a GIF.  However, on conversion from ipynb to HTML the GIF is not copied to an images directory nor is there a line in the corresponding HTML which references a GIF.  It seems as if nbsphinx is completely ignoring the file.  Is there some setting I may be missing for the `conf.py` to pull in GIFs ?

IPYNB: https://github.com/dask/dask-tutorial/blob/master/01x_lazy.ipynb
HTML OUTPUT: https://tutorial.dask.org/01x_lazy.html

**Comment by TomAugspurger** [comment]
As a note of followup, the GIF is handled well when markdown syntax is used

```
![img](path/to/gif.gif)
```

It failed to be included in the built HTML when writing HTML directly

```
<img src="path/to/gif"/>
```

**Comment by mgeier** [comment]
@quasiben Does that answer your question?

**Comment by quasiben** [comment]
Not exactly.  Ideally, nbsphinx should pick up the markdown syntax of a gif as it does with a png/jpeg.  But if you want to close that's ok with me

**Comment by mgeier** [comment]
@quasiben No, I don't necessarily want to close this, I just wanted to know if I have to look into this.

Right now, the GIF if shown in your HTML link above, so can you please clarify what's the actual problem?

**Comment by mgeier** [comment]
This may or may not be fixed by #438. I'm closing it anyway due to lack of response.

**Comment by hakonanes** [comment]
> It failed to be included in the built HTML when writing HTML directly
> 
> ```
> <img src="path/to/gif"/>
> ```

This HTML syntax displayed my GIF nicely (bottom of this section): https://kikuchipy.org/en/latest/visualizing_patterns.html#Plot-multiple-signals

---

BTW, thanks *a lot* for `nbsphinx`, it makes writing Sphinx documentation much more fun :tada:
