### ISSUE TITLE
The sphinx_copybutton extension doesn't properly work out-of-the-box

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#333]
The extension adds "copy" buttons to all code areas, including Jupyter code cells, see https://github.com/choldgraf/sphinx-copybutton.

Some CSS to work around the issue is shown in https://github.com/spatialaudio/nbsphinx/issues/330#issuecomment-538772288, but it would certainly be nice to make this work out-of-the-box.

Currently, there are several problems:

* the copy buttons are also shown for the prompts, which is quite useless
* the distance from the top and right edge of the code cell is too large (and much larger than it is in "normal" code blocks)
* in Chrome, scrollbars appear on code cells with a single line

Firefox:

![image](https://user-images.githubusercontent.com/705404/66330918-ac021e00-e931-11e9-9247-987b0d8c094c.png)

Chrome:

![image](https://user-images.githubusercontent.com/705404/66331010-e10e7080-e931-11e9-8e16-61e78f4c0d91.png)

**Comment by choldgraf** [comment]
Could you give this a shot with the latest sphinx-copybutton and see if it works now? Some recent PRs should have cleaned up the CSS a bit

**Comment by mgeier** [comment]
@choldgraf I have just merged #349 with a few fixes on the `nbsphinx` side of things.

I've also re-based all my theme branches to check it on a variety of themes.

It mostly works great!
But there are a few issues:  #376
