### ISSUE TITLE
sphinx 2.2?

### ISSUE THREAD

**Issue by rddaz2013** [spatialaudio/nbsphinx#354]
Can someone prove that the latest version of nbsphinx works with sphinx higher as 1.8.5?
with sphinx >=2 i get an error because of the six module.

René

**Comment by mgeier** [comment]
I'm using it with the `master` version of Sphinx and it works.

Travis-CI is running Sphinx 2.2.1, see e.g. https://travis-ci.org/spatialaudio/nbsphinx/jobs/614461565

Furthermore, 2.0.0, 2.1.0 and 2.1.2 have been checked.

CircleCI is also running Sphinx 2.2.1, see e.g. https://app.circleci.com/jobs/github/spatialaudio/nbsphinx/87

I've added a check for Sphinx 2.2.0 in #356, which also passes.

----

Can you please provide the full error message and ideally a minimal example to reproduce the error?

**Comment by rddaz2013** [comment]
Nice,

"Can you please provide the full error message and ideally a minimal example to reproduce the error?" sorry no - because i use a very very old version of nbsphinx so a had to use sphinx 1.8.5 but this still works.

Now i have to update my nbsphinx version to the latest version from you - without losing to much of my modifications. It's always like that if you leave a code a year untouched and suddenly forced to reactivate it ^ ^. But thanks for your efforts with this tool has already saved me a lot of time.

**Comment by mgeier** [comment]
I'm not sure if I'm supposed to do anything here.

@rddaz2013 Can you please provide further information (or close this issue if you consider it resolved)?
