### ISSUE TITLE
Equation autonumbering failed with cases environment

### ISSUE THREAD

**Issue by wklchris** [spatialaudio/nbsphinx#357]
When I use the `cases` environment in a Markdown cell, the auto-numbering doesn't work. As a minimal working example, create a Markdown cell in a Jupyter notebook file with following lines:

```
Equation with `cases` environment cannot be autonumbered:

$$ \begin{equation}
f(x) = \begin{cases}1, & x > 0, \\
0, & x \leq 0. \end{cases}
\label{eq-one}
\end{equation}$$

We cite $\eqref{eq-one}$ here.
```

Some quick notes:

- If change the `cases` equation into something simple (e.g. `a = b + c`), the autonumbering works. That means I didn't configure `conf.py` file wrong.
- I've confirmed that the Jupyter Notebook extension can handle `cases` numbering (when I edit the ipynb file, it displays the equation number properly), so I think it's probably a nbsphinx's issue (instead of MathJax's).

Running under Sphinx 2.2.1 with nbsphinx 0.5.0.

**Comment by mgeier** [comment]
You should never use double dollars, see http://ctan.space-pro.be/tex-archive/info/l2tabu/english/l2tabuen.pdf#subsection.1.6

What happens if you simply remove them?

**Comment by wklchris** [comment]
> You should never use double dollars, see http://ctan.space-pro.be/tex-archive/info/l2tabu/english/l2tabuen.pdf#subsection.1.6
> 
> What happens if you simply remove them?

Yes, removing double dollars works. Thanks.

Actually I never use `$$` in LaTeX files, I just thought it was a "have-to" for Jupyter Notebook (which is obviously wrong). For anyone who may read this issue, please use LaTeX environments directly (e.g. `equation`, `align`, `gather` and their asterisk-variants like `equation*` ).

Thank you again for stopping me from being incorrect and silly. This issue can be closed.
