### ISSUE TITLE
Use github actions as CI

### ISSUE THREAD

**Issue by s-weigand** [spatialaudio/nbsphinx#361]
Last month github released github actions as CI service and the test runners are [a lot more 'buffed'](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) than the ones on travis or circleCI. Also you can run up to 20 concurrent builds, which would greatly reduce the time you need to wait for the CI results (especially on MacOs). It also supports artifact upload, which I think is the only use of the CircleCi test. 
If you want to change your CI service I can make a PR for that, since I'm pretty used to it by now, after transitioning most of my own projects.

**Comment by mgeier** [comment]
Yes please, that would be great!

> It also supports artifact upload, which I think is the only use of the CircleCi test.

Well yes, and it also tests if the artifacts can be built in the first place, especially the PDF version.

The real point isn't artifact uploading, but the automatic hosting of the artifacts (without jumping through hoops). Can Github Actions do that, too?

**Comment by s-weigand** [comment]
I don't fully understand the `automatic hosting` part :sweat_smile: 
The Actions themselves aren't public (you need to be logged into github to see them) for security reasons, so external resources can't access them.
But you can upload artifacts in a job and download them from it as well ([see](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts)).

**Comment by mgeier** [comment]
With "automatic hosting" I mean that the artifacts are provided for direct download by the Action itself, without having it to upload to some user-specified third-party server.

The [upload-artifact](https://github.com/actions/upload-artifact) action seems to do that, but it looks like it provides all artifacts as `.zip` archives, which is totally annoying.
I would like to get a link to a PDF where I can click on and see the PDF, without having to download a `.zip` file and unpacking it.

Same for the HTML files. Getting them as `.zip` file would be annoying, wouldn't it?

But anyway, it would still be nice to replace Travis-CI with Github Actions!

**Comment by s-weigand** [comment]
I see your point and there is [quite a huge demand for that feature](https://github.com/actions/upload-artifact/issues/3) hopefully `v2` will be out sometime soon, until then CircleCi seems more practical.

**Comment by mgeier** [comment]
See also #358.

**Comment by s-weigand** [comment]
Looks like `v2` [will get the option to host single files](https://github.com/actions/upload-artifact/issues/7#issuecomment-566114993), I will postpone the work on this and see how it plays out. 'mid-January' isn't far anyway 😋

**Comment by mgeier** [comment]
Just a little update: It is now possible to *upload* single files and whole directories without zipping them, but the Github *GUI* cannot yet display them properly. For now, each artifact is still provided as ZIP files.

**Comment by s-weigand** [comment]
Thx for the info, I saw that there was an update, but I didn't yet have time to play around with it and see how it goes.

**Comment by mgeier** [comment]
I think this can be closed, any follow-up discussions can be held at #495.
