### ISSUE TITLE
Widget output is duplicated

### ISSUE THREAD

**Issue by janfreyberg** [spatialaudio/nbsphinx#378]
Hi all,

for some reason, I am seeing my widgets twice. I am developing a jupyter widget, and am trying to build documentation that has them as interactive HTML elements.

My process is:

- create and display the widget in a notebook
- save the notebook using the Jupyter Notebook menu `Widgets` -> `Save Notebook Widget State`
- run `make html` in my documentation folder, where I have `nbsphinx` listed as an extension.

However, this produces something that looks like this:
![image](https://user-images.githubusercontent.com/4092425/72243607-42567780-35e4-11ea-809b-199ba1cc4a80.png)

Meanwhile, in the notebook, it looks like this:
![image](https://user-images.githubusercontent.com/4092425/72243804-bbee6580-35e4-11ea-8f3c-b3fdf8903f41.png)

I should note that this is true for both my custom widgets and simple ipywidgets, e.g. `Button`.

Environment is:
```
python==3.7.5
ipywidgets==7.5.1
jupyter-sphinx==0.2.3
nbsphinx==0.5.0
sphinx-automodapi==0.12
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
```

(I have other libraries installed but these seem the most relevant).

**Comment by janfreyberg** [comment]
🤦‍♂  I'm sorry for opening this issue before playing around with it myself: what solved the issue for me was removing jupyter-sphinx from the configuration / installation.

Of course feel free to close the issue but I'll leave it open just in case you know why this might be and if there's a way to fix it?

It still would be nice to be able to use both in a project together.

**Comment by mgeier** [comment]
Thanks for the report!

The reason for this duplication is that a line like this is appearing twice in your HTML files:

    <script type="text/javascript" src="https://unpkg.com/@jupyter-widgets/html-manager@^0.18.0/dist/embed-amd.js"></script>

There are three ways to avoid this duplication:

* not using `nbsphinx`
* not using `jupyter_sphinx`
* setting [nbsphinx_widgets_path](https://nbsphinx.readthedocs.io/en/0.5.0/usage.html#nbsphinx_widgets_path) to the empty string

**Comment by janfreyberg** [comment]
Ah cool! Thanks - that makes a lot of sense!
