### ISSUE TITLE
rst_prolog and rst_epilog break notebook loading

### ISSUE THREAD

**Issue by wkerzendorf** [spatialaudio/nbsphinx#38]
Any ideas. Here is the log:
[sphinx-err-glebxw.txt](https://github.com/spatialaudio/nbsphinx/files/216808/sphinx-err-glebxw.txt)

**Comment by mgeier** [comment]
`nbformat` seems to have problems reading the notebook.
Can you try to upgrade the `nbformat` package?

If that doesn't change anything, can please you provide the notebook in question?
Or a stripped-down version that still produces the error?

**Comment by wkerzendorf** [comment]
```bash
docs git:(master) ✗ conda install nbformat
Fetching package metadata: ....
Solving package specifications: ..............
# All requested packages already installed.
# packages in environment at /Users/wkerzend/anaconda3/envs/xtool:
#
nbformat                  4.0.1                    py27_0 
```

**Comment by wkerzendorf** [comment]
Thanks for your help

https://github.com/eso/xtool/blob/master/docs/notebooks/cookbook_fitting.ipynb

**Comment by mgeier** [comment]
Your notebook works for me in both Python 2.7 and 3.5, I could simply include it in the `nbsphinx` docs.

Can you try to uninstall `nbformat` and re-install it again?

Or probably try everything in a fresh virtual environment?

I couldn't run your Sphinx build though, because there was no `setup.cfg`.

**Comment by mgeier** [comment]
You could also try to isolate the problem with this:

```python
import nbformat
nbformat.read('cookbook_fitting.ipynb', 4)
```

**Comment by wkerzendorf** [comment]
That works: 

```python
nbformat.read('notebooks/cookbook_fitting.ipynb', 4)
Out[4]: 
{u'cells': [{u'cell_type': u'markdown',
   u'metadata': {},
   u'source': u'### Modelling XShooter data with xtool ###'},
  {u'cell_type': u'code',
```

**Comment by wkerzendorf** [comment]
Here is the conf: https://github.com/eso/xtool/blob/master/docs/conf.py

**Comment by mgeier** [comment]
I get `NoSectionError: No section: 'metadata'` and I suspect that's because there is no `setup.cfg`.

But anyway, can you please try to make a new Sphinx project just including this one notebook and see if that works?

**Comment by wkerzendorf** [comment]
Found this now: *** ValueError: Extra data: line 295 column 1 - line 298 column 1 (char 5900 - 5934)
I can run sphinx and jump into the debugger.But these lines do not exist. Is anything injecting something into the string?

**Comment by wkerzendorf** [comment]
okay got it - `rst_epilog` - variable was to plain that inserts the string in there: `rst_epilog = """` did the trick.

**Comment by mgeier** [comment]
Ah, that's interesting! I've never used those config options before ...

I didn't find a way to disable those only for notebooks, you'll have to do without them for now.
I've created an issue for Sphinx: https://github.com/sphinx-doc/sphinx/issues/2445.
Hopefully, in a future Sphinx version this will be supported.

**Comment by mgeier** [comment]
If all goes well, this will be fixed in Sphinx version 1.4.2.

**Comment by mgeier** [comment]
This was fixed in Sphinx 1.4.2.

It would still be nice to have a similar feature that works with notebooks, e.g. to add custom download links, see #5.

**Comment by adrn** [comment]
@mgeier I hit this same issue with Sphinx 1.5.1 and nbsphinx 0.2.12. I tracked it down to the fact that the `NotebookParser` subclasses the `rst.Parser` but doesn't updated the `supported` attribute (see [this line](https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/__init__.py#L84)), so  `get_parser_type()` in Sphinx ([here](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/io.py#L161)) returns `('restructuredtext', 'rst', ...)`

I got it to work by adding this to the `NotebookParser` subclass definition, but that was a hack and I don't know enough about the details of Sphinx to know whether the names I made up are relevant :) :

```python
class NotebookParser(rst.Parser):
    supported = ('ipynb', 'ipy', 'ipython-notebook')
    ...
```

**Comment by mgeier** [comment]
Thanks @adrn, I wasn't aware of this attribute.

I have no clue what kind of names we are supposed to use, but it looks like the are just arbitrarily made up and they might clash with any other parser.

Since we don't actively use this feature, what about setting it to

```pyton
supported = ()
```

?
Does it still work then?
If yes, would you mind making a PR for that?
