### ISSUE TITLE
Add missing themes to docs

### ISSUE THREAD

**Issue by s-weigand** [spatialaudio/nbsphinx#381]
[The docs](https://nbsphinx.readthedocs.io/en/0.5.0/usage.html#HTML-Themes) only mention 27 out of 31 themes, which are build by RTD.

**Comment by mgeier** [comment]
Thanks!

There are actually 32 themes, if I didn't make a mistake ...

Those seem to be the 5 missing ones:

1. https://nbsphinx.readthedocs.io/en/alabaster-jupyterhub-theme/
1. https://nbsphinx.readthedocs.io/en/astropy-theme/
1. https://nbsphinx.readthedocs.io/en/dotted-theme/
1. https://nbsphinx.readthedocs.io/en/material-theme/
1. https://nbsphinx.readthedocs.io/en/sphinxdoc-theme/

Do you want to add them?

**Comment by s-weigand** [comment]
Sure, I can do that, but where does `dotted-they come from?

I can't find a branch called `dotted-theme`, which would be needed to create the usage link.

**Comment by mgeier** [comment]
Oh yeah, sorry, that's why we had a different count!

I had forgotten: some time ago the build of the `dotted` theme started to fail on RTD and I decided to simply remove it (because I don't think it's an important theme).

But it looks like I only removed the branch from Github and didn't remove it from RTD.

But just now I removed it, so we are really at 31 themes.

**Comment by s-weigand** [comment]
Actually only [alabaster-jupyterhub](https://nbsphinx.readthedocs.io/en/alabaster-jupyterhub-theme/) did miss. I got no idea how I got 27, guess it was just late.

Found this working on #376 , when i couldn't find `astropy` since it is called `bootstrap-astropy`, sleepy noob me 😝 .

**Comment by mgeier** [comment]
> I got no idea how I got 27, guess it was just late.

I also missed this, but your link in the original issue description is for the `0.5.0` version https://nbsphinx.readthedocs.io/en/0.5.0/usage.html#HTML-Themes with 27 themes, while the `master` branch https://nbsphinx.readthedocs.io/en/latest/usage.html#HTML-Themes has 30 themes in the list.
