### ISSUE TITLE
Plots in Subdirectories

### ISSUE THREAD

**Issue by llchan** [spatialaudio/nbsphinx#394]
I believe plots in notebooks in subdirectories have incorrect urls due to https://github.com/jupyter/nbconvert/issues/293.  Can someone confirm?  I currently have a horribly hacky workaround involving regular expressions on the rst output, but hopefully we can come up with a more permanent solution (either here or upstream in nbconvert).

**Comment by mgeier** [comment]
Thanks for the report!

The issue you are mentioning is quite old, so I would be surprised if it wasn't known. Could the problem be #49?

If not, can you please provide a minimal example project?

Notebooks in subdirectories should generally work, as shown in https://nbsphinx.readthedocs.io/en/0.5.1/subdir/a-notebook-in-a-subdir.html.

**Comment by llchan** [comment]
Ah youre totally right.  I had seen that issue and switched the notebooks to be copies rather than symlinks, but turns out a parent dir further up in the hierarchy was a symlink.  Can close this and leave discussion to the other ticket.
