### ISSUE TITLE
Link miss

### ISSUE THREAD

**Issue by LovelyBuggies** [spatialaudio/nbsphinx#403]
In the part of Sphinx setup of Usage, a link (this project's) misses:

> For an example, see this project’s doc/index.rst file.

**Comment by mgeier** [comment]
Thanks for the report!

This is no link on purpose, though.

If this were a link to `index.rst`, `nbsphinx` would turn it into a link to `index.html`, which wouldn't be helpful here.

Or would you expect the link to point somewhere else?

Or do you mean the text "this project's" should become a link?

**Comment by LovelyBuggies** [comment]
Yes, I propose the text "this project's" should become a link. I know it may link to this repo, but it doesn't hurt if not.

**Comment by mgeier** [comment]
OK, where should it link to?

Would you like to make a PR?
