### ISSUE TITLE
No render equations with sphinxcontrib-katex

### ISSUE THREAD

**Issue by carlosal1015** [spatialaudio/nbsphinx#409]
Hello, my issue report is the following:

I installed in two python 3.8.2 environment the packages `sphinx==2.4.4`, `sphinxcontrib-katex==0.6.0` and `nbsphinx==0.5.1`, indeed, the last versions of each one. I want to use KaTeX instead of MathJax.

I did an experiment and isolated two Sphinx projects called 1 and 2 with the packages mentioned above, the only difference between these is `conf.py`.
![DeepinScreenshot_select-area_20200316112602](https://user-images.githubusercontent.com/21283014/76779099-cfe74c80-6778-11ea-99ed-9fb602d45ad0.png)
![DeepinScreenshot_select-area_20200316112634](https://user-images.githubusercontent.com/21283014/76779104-d249a680-6778-11ea-853e-d30fb97a9b5e.png)
i.e, 1 load `sphinxcontrib-katex` and 2 load `sphinxcontrib-katex` and `nbsphinx`. Then, when I build both projects and put some math in the front page:
![DeepinScreenshot_select-area_20200316114439](https://user-images.githubusercontent.com/21283014/76780553-438a5900-677b-11ea-97d0-68c949db17d2.png)
Whose sources HTML generated by Sphinx are
![DeepinScreenshot_select-area_20200316121745](https://user-images.githubusercontent.com/21283014/76783453-de853200-677f-11ea-901f-ea7c81a9c4e4.png)
Hence, there are similar, the difference match on line 17 on 2.
![DeepinScreenshot_select-area_20200316110719](https://user-images.githubusercontent.com/21283014/76777308-02dc1100-6776-11ea-88f2-3f767a402bd8.png)
And render the math (if I comment the line 17 in `index.html` from 2):
![DeepinScreenshot_select-area_20200316110801](https://user-images.githubusercontent.com/21283014/76777392-2010df80-6776-11ea-94fc-26cc0c7032cb.png)
![DeepinScreenshot_select-area_20200316114124](https://user-images.githubusercontent.com/21283014/76780550-41c09580-677b-11ea-95ec-dded6d71023d.png)
Please, could you review this behavior? Maybe the issue will be on [`sphinxcontrib-katex`](https://pypi.org/project/sphinxcontrib-katex/) and not in [`nbsphinx`](https://pypi.org/project/nbsphinx/).

Thank you.

**Comment by mgeier** [comment]
Thanks for the detailed report!

As a work-around, you should be able to deactivate the inclusion of require.js by using this in your `conf.py`:

```python
nbsphinx_requirejs_path = ''
```

See https://nbsphinx.readthedocs.io/en/0.5.1/usage.html#nbsphinx_requirejs_path.

But it would be nice if we could make KaTeX work together with require.js.

Can you please check the JavaScript console in your browser dev tools for any error/warning messages?

**Comment by carlosal1015** [comment]
Thanks @mgeier, with `nbsphinx_requirejs_path = ''` works fine and no console error/warning :smile:.
![DeepinScreenshot_select-area_20200317103317](https://user-images.githubusercontent.com/21283014/76875821-14d5b680-683f-11ea-86a0-b826f18c5dc1.png)

This the head of `index.html` with same state of 2 plus `nbsphinx_requirejs_path = ''`.
```html
<head>
  <meta charset="utf-8" />
  <title>Welcome to Testing’s documentation! &#8212; Testing  documentation</title>
  <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" />
  <link rel="stylesheet" type="text/css" href="_static/katex-math.css" />
  <script id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
  <script src="_static/jquery.js"></script>
  <script src="_static/underscore.js"></script>
  <script src="_static/doctools.js"></script>
  <script src="_static/language_data.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js"></script>
  <script src="_static/katex_autorenderer.js"></script>
  <link rel="index" title="Index" href="genindex.html" />
  <link rel="search" title="Search" href="search.html" />
 
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
   
   
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head>
```
Maybe we could add in the docs the possibility to use KaTeX if `nbsphinx_requirejs_path = ''` is enabled.

Please, close this issue if consider necessary.

**Comment by mgeier** [comment]
Can you please show the console warnings/errors for the non-working case?

**Comment by carlosal1015** [comment]
Hi @mgeier, there are three errors :warning: .
![DeepinScreenshot_select-area_20200317144836](https://user-images.githubusercontent.com/21283014/76895520-2a0e0d80-685e-11ea-90f6-2395195c2426.png)

The first one is on line 9: `renderMathInElement(document.body, katex_options);`.
```js
Uncaught ReferenceError: renderMathInElement is not defined
    at HTMLDocument.<anonymous> (katex_autorenderer.js:9)
```
```js
// katex_autorenderer.js
katex_options = {

delimiters: [
        { left: "\\(", right: "\\)", display: false },
        { left: "\\[", right: "\\]", display: true }
        ]
}
document.addEventListener("DOMContentLoaded", function() {
  renderMathInElement(document.body, katex_options);
});
```
The second and third are from [`require.min.js`](https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js) (click to go the source or too much legible [here](https://gist.github.com/carlosal1015/89990cfec49a0a84808c4191eab4e443)).
```js
Uncaught Error: Mismatched anonymous define() module: function(){return function(t){var e={};
...
too large characters
the number of characters exceeds the message limit.
... 
{Span:N,Anchor:I,SymbolNode:E,SvgNode:L,PathNode:H,LineNode:P}};e.default=Ca}]).default}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:1)
    at v (require.min.js:1)
    at require.min.js:1
```

```js
Uncaught Error: Mismatched anonymous define() module: function(e){return function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=1)}([function(t,r){t.exports=e},function(e,t,r){"use strict";r.r(t);var n=r(0),o=r.n(n),a=function(e,t,r){for(var n=r,o=0,a=e.length;n<t.length;){var i=t[n];if(o<=0&&t.slice(n,n+a)===e)return n;"\\"===i?n++:"{"===i?o++:"}"===i&&o--,n++}return-1},i=function(e,t,r,n){for(var o=[],i=0;i<e.length;i++)if("text"===e[i].type){var l=e[i].data,d=!0,s=0,f=void 0;for(-1!==(f=l.indexOf(t))&&(s=f,o.push({type:"text",data:l.slice(0,s)}),d=!1);;){if(d){if(-1===(f=l.indexOf(t,s)))break;o.push({type:"text",data:l.slice(s,f)}),s=f}else{if(-1===(f=a(r,l,s+t.length)))break;o.push({type:"math",data:l.slice(s+t.length,f),rawData:l.slice(s,f+r.length),display:n}),s=f+r.length}d=!d}o.push({type:"text",data:l.slice(s)})}else o.push(e[i]);return o},l=function(e,t){for(var r=function(e,t){for(var r=[{type:"text",data:e}],n=0;n<t.length;n++){var o=t[n];r=i(r,o.left,o.right,o.display||!1)}return r}(e,t.delimiters),n=document.createDocumentFragment(),a=0;a<r.length;a++)if("text"===r[a].type)n.appendChild(document.createTextNode(r[a].data));else{var l=document.createElement("span"),d=r[a].data;t.displayMode=r[a].display;try{t.preProcess&&(d=t.preProcess(d)),o.a.render(d,l,t)}catch(e){if(!(e instanceof o.a.ParseError))throw e;t.errorCallback("KaTeX auto-render: Failed to parse `"+r[a].data+"` with ",e),n.appendChild(document.createTextNode(r[a].rawData));continue}n.appendChild(l)}return n};t.default=function(e,t){if(!e)throw new Error("No element provided to render");var r={};for(var n in t)t.hasOwnProperty(n)&&(r[n]=t[n]);r.delimiters=r.delimiters||[{left:"$$",right:"$$",display:!0},{left:"\\(",right:"\\)",display:!1},{left:"\\[",right:"\\]",display:!0}],r.ignoredTags=r.ignoredTags||["script","noscript","style","textarea","pre","code"],r.ignoredClasses=r.ignoredClasses||[],r.errorCallback=r.errorCallback||console.error,r.macros=r.macros||{},function e(t,r){for(var n=0;n<t.childNodes.length;n++){var o=t.childNodes[n];if(3===o.nodeType){var a=l(o.textContent,r);n+=a.childNodes.length-1,t.replaceChild(a,o)}else 1===o.nodeType&&function(){var t=" "+o.className+" ";-1===r.ignoredTags.indexOf(o.nodeName.toLowerCase())&&r.ignoredClasses.every(function(e){return-1===t.indexOf(" "+e+" ")})&&e(o,r)}()}}(e,r)}}]).default}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:1)
    at v (require.min.js:1)
    at require.min.js:1
```

I tried the advice of @hagenw in [this issue](https://github.com/hagenw/sphinxcontrib-katex/issues/28#issuecomment-600238038) to swap the order of the extensions, but I get exactly the above three errors.

Thanks.

**Comment by mgeier** [comment]
Thanks for the error messages. And thanks to search engines, which yield those results:

* https://stackoverflow.com/a/23467090/
* https://requirejs.org/docs/errors.html#mismatch

It looks like require.js should be loaded *after* KaTeX.

Since KaTeX is loaded in `builder-inited` and require.js is loaded in `config-inited`, latter will be loaded first.

I've just created #412 to load require.js in `builder-inited`, too.

With that, it should work, but only if you load `sphinxcontrib-katex` before `nbsphinx` in your `extensions`.

Can you please check if that works for you?

Any ideas how we could make this even independent of the order or `extensions`?

**Comment by mgeier** [comment]
I've come up with a little trick to load require.js even later: b0c36efc08acb2b9e56cd572e2f6bafdd7d72eb2

Now the order of `nbsphinx` and `sphinxcontrib-katex` shouldn't matter anymore!

**Comment by carlosal1015** [comment]
> I've come up with a little trick to load require.js even later: [b0c36ef](https://github.com/spatialaudio/nbsphinx/commit/b0c36efc08acb2b9e56cd572e2f6bafdd7d72eb2)
> 
> Now the order of `nbsphinx` and `sphinxcontrib-katex` shouldn't matter anymore!

Very good @mgeier, I tested the new code on `load-requirejs-later ` branch with the following way:
```sh
git clone -b load-requirejs-later --single-branch --depth=1 https://github.com/mgeier/nbsphinx.git
cd nbsphinx
pipenv install docutils jinja2 nbconvert nbformat sphinx traitlets sphinxcontrib-katex
pipenv shell
mkdir docs # testing_docs
cd docs
sphinx-quickstart
```
I created a Sphinx project in `docs` folder. Now, without put `nbsphinx_requirejs_path = ''` in the `conf.py` file and with this shape:
```python
# docs/souce/conf.py
import sys, os
sys.path.append(os.path.abspath('../../src'))
 # More base code
extensions = [
    'nbsphinx',
	'sphinxcontrib.katex'
]
```
And works no matter whose is first in the extension's list.
![Captura de pantalla 2020-03-18 a la(s) 5 47 23 p  m](https://user-images.githubusercontent.com/21283014/77014572-9cefb500-6940-11ea-89af-3c4861cad4b9.png)
I hope to be able to have this new feature in `nbsphinx` in the next versions to use it in a bigger project.

Thank you.

**Comment by mgeier** [comment]
@carlosal1015 Thanks for testing!

And yes, this will be in the next release, unless somebody finds a problem with it before that.

**Comment by carlosal1015** [comment]
> @carlosal1015 Thanks for testing!
> 
> And yes, this will be in the next release, unless somebody finds a problem with it before that.

Thanks you @mgeier, in a [project](https://scientificpython.readthedocs.io/en/latest/changes.html) with `nbsphinx 0.6.0` and KaTeX works jointly without `nbsphinx_requirejs_path = ''`.
