### ISSUE TITLE
Widgets are not rendered when running parallel build

### ISSUE THREAD

**Issue by thangleiter** [spatialaudio/nbsphinx#414]
`tqdm` widgets do not render on [our readthedocs](https://filter-functions.readthedocs.io/en/latest/). Instead, there is only white space.

If I build the documentation locally, I can reproduce this effect if I run the build in parallel, e.g.
```shell
sphinx-build -b html . _build/html -j4
```
whereas if I skip the parallel flag, the widgets render fine (see screencaps below)

Locally, at least, this is independent of whether `nbsphinx` executes the notebooks or simply parses them if they have saved output cells.

Thanks for your work on this project, it makes generating an interactive documentation a breeze!

![image](https://user-images.githubusercontent.com/32895729/77168467-2a094a00-6ab8-11ea-96e9-db333991785b.png)
vs.
![image](https://user-images.githubusercontent.com/32895729/77168550-4ad19f80-6ab8-11ea-9db7-c914b9e1fd1c.png)

**Comment by mgeier** [comment]
Thanks for the report! I can reproduce the problem.

It looks like the necessary JavaScript is not included, which is supposed to be included there:

https://github.com/spatialaudio/nbsphinx/blob/96e8b4c700e4dc6c35ab8436245d13754d766d99/src/nbsphinx.py#L1700-L1701

For some reason this doesn't seem to work with parallel builds.

I'll have to look into this. If you have any ideas how to fix this, please let me know!

**Comment by mgeier** [comment]
I found the problem: I hadn't implemented the `env-merge-info` event, which is necessary to update the main environment in case of parallel builds.

I've implemented the event in #456, can you please check if this works for you?

**Comment by thangleiter** [comment]
This works for me, thanks a bunch!

**Comment by mgeier** [comment]
Great, thanks for testing this!
