### ISSUE TITLE
Current working directory for notebook execution

### ISSUE THREAD

**Issue by dmey** [spatialaudio/nbsphinx#433]
What is the current working directory used nbsphinx when executing notebooks? Can this be specified? I am having an issues with a notebook that uses `pathlib.Path.cwd()` and therefore this is relative to where the notebook is executed.

**Comment by mgeier** [comment]
> What is the current working directory used nbsphinx when executing notebooks?

The directory where the notebook is stored:

https://github.com/spatialaudio/nbsphinx/blob/37bc1c21c8f63db33cd04a2aa17438e7db197d2a/src/nbsphinx.py#L952-L953

> Can this be specified?

No.

It doesn't really make sense to execute it anywhere else, or does it?

> I am having an issues with a notebook that uses `pathlib.Path.cwd()` and therefore this is relative to where the notebook is executed.

Can you please provide a minimal example?

**Comment by dmey** [comment]
> It doesn't really make sense to execute it anywhere else, or does it?

As the current working directory is the directory where the notebook is stored, I'd agree that there is probably no reason to support other use cases.

Thank you -- I will close this now

**Comment by mgeier** [comment]
I would still be interested in your original problem.

Maybe there is something we can do to fix it?

**Comment by dmey** [comment]
> I would still be interested in your original problem.
> 
> Maybe there is something we can do to fix it?

Thanks -- I double checked this now and it appears that my issue was not due to this but rather to the fact that one of the cells (the one containing `var = pathlib.Path.cwd()`) had previously been generated in the notebook and saved and nbsphinx 'failed' to generate the corresponding notebook (as part of it was already present). I have debugged this better and as you pointed out, the current working directory is the directory where the notebook is stored so, all good re this issue. 

Separately, what I think may be useful in this case is to 'force' the re-generation of notebooks. Is this currently possible? Let me know if you want this to be moved.

**Comment by mgeier** [comment]
OK, thanks, it's good to know that everything works as expected.

> Separately, what I think may be useful in this case is to 'force' the re-generation of notebooks. Is this currently possible?

I'm not sure what you mean.

There is `nbsphinx_execute = 'always'`?

https://nbsphinx.readthedocs.io/en/0.6.0/usage.html#nbsphinx_execute

> Let me know if you want this to be moved.

I don't mind.

But if you want to request a new feature, it's probably better to open a new issue.
