### ISSUE TITLE
All the ipywidgets show twice in the readthedocs

### ISSUE THREAD

**Issue by dou-du** [spatialaudio/nbsphinx#460]
I am working on a custom Jupyter widget. After creating the readthedos, I found all the widgets show twice. Here is the link:

 https://osscar-docs.readthedocs.io/en/latest/widgets/periodictable.html

Could you help me to fix it ? Thanks a lot.

**Comment by mgeier** [comment]
This looks very much like #378?

**Comment by dou-du** [comment]
> This looks very much like #378?

Thanks a lot. It is working now.
