### ISSUE TITLE
PDF Conversion failing in nbconvert docs builds with 0.7.0

### ISSUE THREAD

**Issue by MSeal** [spatialaudio/nbsphinx#474]
I had to pin nconvert's docs build to 0.6.1 to get it to build again. There's an error with an invalid png (only header written in the file it appears?) being generated by latexmk based on converting the results of `python3 setup.py build_sphinx -b latex`. I tried a few things to correct for the issue but didn't find a root cause in the change. It appears to have begun failing off the master build of nbsphinx between the 7th and 18th of March (the builds used to use git master during doc gen). https://github.com/jupyter/nbconvert/blob/master/.circleci/config.yml has the execution commands that fail on the `latexmk -pdf` task using the latest release of nbsphinx. If you nuke the `build` directory and rerun with 0.6.1. it succeeds.

**Comment by mgeier** [comment]
This error was due to multi-line data in an `<img src="data:...">` tag in a notebook:

https://github.com/jupyter/nbconvert/blob/e67aad48c293071149125aeaf0e8980b988ecf5e/docs/source/customizing.ipynb#L24691-L24693

I've created a fix in #475.

**Comment by MSeal** [comment]
Thanks! I'll unpin our doc builds once that fix is released. Appreciate you digging into the issue.

**Comment by mgeier** [comment]
@MSeal I've just released `nbsphinx` 0.7.1 which contains the fix.

**Comment by MSeal** [comment]
@mgeier Great, looks like it's working. I'll change the pin to `>=0.7.1`
