### ISSUE TITLE
output prompt not displaying in html

### ISSUE THREAD

**Issue by DevinShanahan** [spatialaudio/nbsphinx#480]
By default, my html is rendering with only the input prompt.

I have added the following in my `conf.py`
```python
nbsphinx_input_prompt = 'In [%s]:'
nbsphinx_output_prompt = 'Out [%s]:'
```
But I am still only getting the input prompt.

Is there something I need to do to display the output prompt? Is this an `nbconvert` issue?

Thanks.

Python: 3.6.10
nbsphix: 0.7.1

**Comment by mgeier** [comment]
This is strange ...

Can you please provide a minimal example project to reproduce this problem?

**Comment by DevinShanahan** [comment]
Ah, while generating a minimal example, I have diagnosed the problem.

I am using functions that print to stdout which, I hadn't ever realized, does not generate an output prompt.

```python
In [1]: 3                                                                       
Out[1]: 3

In [2]: print(3)                                                                
3
```

**Comment by mgeier** [comment]
That's why minimal examples are great!

Thanks for the update, and don't hesitate to report any other problems you might have.
