### ISSUE TITLE
Syntax coloring works locally, not on RTD

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spatialaudio/nbsphinx#482]
[RTD](https://dev-tg.readthedocs.io/en/latest/examples/misc/timeseries.html); works locally:

![image](https://user-images.githubusercontent.com/16495490/89731820-207a8180-da5b-11ea-9cb2-d1f18407944c.png)

Possible causes?

And thanks for the extension, a must-have for some uses.

**Comment by mgeier** [comment]
https://nbsphinx.readthedocs.io/en/0.7.1/installation.html#Pygments-Lexer-for-Syntax-Highlighting

**Comment by OverLordGoldDragon** [comment]
@mgeier Thanks.

For clarity: ensure `IPython` is included in RTD's build (via e.g. `requirements.txt` in `.readthedocs.yml`).
