### ISSUE TITLE
Hide cell output

### ISSUE THREAD

**Issue by boba-and-beer** [spatialaudio/nbsphinx#493]
I wasn't able to find any function that hide the cell output inside the Jupyter Notebook (specifically I want to keep the code but hide the cell because the cell output is so long!) Can anyone please point me in the right direction? 

Example of what I want to achieve: 

```
>>> print("Hi")
```

**Comment by mgeier** [comment]
This is currently not possible, but there is an open PR: https://github.com/spatialaudio/nbsphinx/pull/436

**Comment by boba-and-beer** [comment]
Thanks! Closing issue  to follow the PR :+1:
