### ISSUE TITLE
HTML: Add download link for the current notebook

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#5]
Ideally, this should already work with the "Source" link (but currently it doesn't).

We could also include an (optional) link above or below the first section title (like [here](http://dimarray.readthedocs.org/en/latest/_notebooks_rst/tutorial.html)) or at the bottom of the page (like [here](http://sphinx-gallery.readthedocs.org/en/latest/auto_examples/plot_exp.html)).

**Comment by mgeier** [comment]
It would probably also be nice, instead of having a link to a copy of the file, to have a link to the Github/Bitbucket page of the (proper version of the) notebook.

These links might be interesting:
https://pypi.python.org/pypi/sphinxcontrib-srclinks
https://gist.github.com/MantasVaitkunas/7c16de233812adcb7028
http://mg.pov.lt/blog/sphinx-edit-on-github.html

**Comment by mgeier** [comment]
I just asked for this on the sphinx-dev mailing list: https://groups.google.com/forum/#!topic/sphinx-dev/q8dGyV6dN4A

**Comment by mgeier** [comment]
I've create a PR for Sphinx: https://github.com/sphinx-doc/sphinx/pull/2399

**Comment by mgeier** [comment]
I've mentioned the option `html_sourcelink_suffix` in 8566fe76b993a7ef669aef02b7216f3b0cac33f8.

**Comment by ketch** [comment]
Just for others who arrive here, the quick solution (not yet in the docs, as far as I can tell) is to add the following to conf.py:

    html_sourcelink_suffix = ''

Then if one right-clicks on the "show source" link and saves the file, it will have the correct .ipynb extension.

It would still be nice to add a more obvious link to download the notebook (in my opinion).

**Comment by mgeier** [comment]
@ketch Thanks for mentioning that. I consider [doc/conf.py](../blob/master/doc/conf.py) part of the documentation, therefore it is documented. If you think it should also be mentioned somewhere else in the documentation, please make a PR!

> It would still be nice to add a more obvious link to download the notebook (in my opinion)

Definitely!
I'm hoping for contributions!

**Comment by mgeier** [comment]
@ketch 

> It would still be nice to add a more obvious link to download the notebook (in my opinion).

I've just created #150, which could be used to create an arbitrarily obvious download link.

What do you think about it?

**Comment by mgeier** [comment]
I've just released version 0.3.0, which includes the options `nbsphinx_prolog` and `nbsphinx_epilog`, which can be used to create download links, see http://nbsphinx.readthedocs.io/en/0.3.0/prolog-and-epilog.html.
