### ISSUE TITLE
Include from relative path

### ISSUE THREAD

**Issue by CsatiZoltan** [spatialaudio/nbsphinx#503]
If the .ipynb file is not in the same directory as the .rst file in which I refer to it, how can I make it work?

## Example:

*my_rst.rst:*
```
.. toctree::
   :maxdepth: 2

   notebooks
```

*notebooks.rst:*
```
Notebooks
=========

.. include:: ../../notebooks/applications/one_of_my_notebooks.ipynb
```

does not use `nbsphinx` to display the notebook:

![Screenshot from 2020-10-16 17-43-46](https://user-images.githubusercontent.com/12742890/96279680-4a11d500-0fd7-11eb-9190-605b8b417600.png)

**Comment by CsatiZoltan** [comment]
OK, this is not supported as written in the [documentation](https://nbsphinx.readthedocs.io/en/0.7.1/links.html). I tried [nbsphinx-link](https://github.com/vidartf/nbsphinx-link), which works just fine. Any reason why not supporting it by default?

**Comment by mgeier** [comment]
> Any reason why not supporting it by default?

Yes, see https://github.com/spatialaudio/nbsphinx/pull/33.
