### ISSUE TITLE
output representation ignored when converted to PDF

### ISSUE THREAD

**Issue by actsasgeek** [spatialaudio/nbsphinx#514]
As I mentioned in the other issue, I use nbsphinx to render notebooks as PDF books and I'm having a bit of trouble getting objects to appear "right".

The main example is Pandas DataFrames. They appear a nice, neat HTML in the Notebook:

<img width="579" alt="Screen Shot 2020-10-23 at 4 19 26 PM" src="https://user-images.githubusercontent.com/216816/97050587-a0d55c80-154b-11eb-8352-455cd6cf8fd5.png">

but they're plaintext in the PDF:

<img width="685" alt="Screen Shot 2020-10-23 at 4 23 17 PM" src="https://user-images.githubusercontent.com/216816/97051214-c6169a80-154c-11eb-8fbe-5a29a2b313a2.png">

And the same thing happens with my own objects. Jupyter Notebook lets you specify `_repr_html_`, `_repr_latex_`, `_repr_markdown_`, etc. for custom (one's own) objects but I always get the default _repr_ something like:

<Foo object at 0x7fbe380aa400>

in the PDF.

Looking in the notebook's JSON, there are values for the various mime types corresponding to `_repr_html_`, `_repr_latex_`, `_repr_markdown_` but I can't figure out how to get nbsphinx to use them. I did a bit in the source code with no luck.

Perhaps this is an easy fix or if I were pointed in the right direction...

**Comment by mgeier** [comment]
Did you read the docs?

Pandas DataFrames are explicitly mentioned (including a link to an explanation why plain text is used by default):

https://nbsphinx.readthedocs.io/en/0.8.0/code-cells.html#Pandas-Dataframes

https://nbsphinx.readthedocs.io/_/downloads/en/0.8.0/pdf/#subsubsection.4.3.5

As for the other cases, the LaTeX output should use `_repr_latex_` if everything works correctly.

This is the display priority for LaTeX:

https://github.com/spatialaudio/nbsphinx/blob/98005a9d6b331b7d6d14221539154df69f7ae51a/src/nbsphinx.py#L79-L87

If any of this doesn't work as expected, please provide a minimal reproducible example, then I can look into it.

**Comment by actsasgeek** [comment]
Matthias,

Thank you for your comments. I think it's fair to say that I haven't ready the docs _lately_. I've used nbsphinx for quite a while (thank you!), I got sidetracked by a dissertation, and then have come back to some long standing issues. I didn't think to look at the docs to see if anything had changed (d'oh!).

I'll give it all another try and let you know one way or the other.

Cheers,
Stephyn

**Comment by actsasgeek** [comment]
This all worked out very well.

The only issue I saw--and definitely not your fault--was that Series print out as plaintext instead of HTML  in Notebooks (I've never understood why that's the default). Because of whatever priority list there is for mime types, Series get shown as LaTeX in Notebooks. I just wrap them in a DataFrame and all is well but that's probably a bug in Pandas.

Thanks again and sorry for not **re**reading the documentation!
