### ISSUE TITLE
nbconvert 6 compatibility ?

### ISSUE THREAD

**Issue by jsalort** [spatialaudio/nbsphinx#517]
Maybe this is a duplicate but I didn't find it on the issue tracker. I have nbsphinx 0.8.0 from PyPI.
`make html` fails when nbconvert 6 is installed. If I roll back to nbconvert 5.6.1, it works.

Here is the error message:
```
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 601, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'rst' found in the following paths:
	/Users/jsalort/Library/Jupyter
	/Users/jsalort/mp38/share/jupyter
	/opt/local/share/jupyter
```

**Comment by mgeier** [comment]
Yeah, there have been some problems with `nbconvert` 6, but I was hoping they are resolved by now.

It might help to uninstall the old version and then try reinstalling?

See also https://github.com/jupyter/nbconvert/issues/1442.

If the problem doesn't go away, please provide a minimal reproducible example, so I can see if I can reproduce the problem.

**Comment by jsalort** [comment]
> Yeah, there have been some problems with `nbconvert` 6, but I was hoping they are resolved by now.
> 
> It might help to uninstall the old version and then try reinstalling?

You are right...
I have tried removing my venv, and recreating it, and now nbphinx works with nbconvert 6.
So I suppose there were some old files that were interfering...
Sorry about the noise.

**Comment by mgeier** [comment]
No problem, have fun!
