### ISSUE TITLE
.ipynb as the homepage?

### ISSUE THREAD

**Issue by LayneSadler** [spatialaudio/nbsphinx#522]
Thank you for the awesome extension. I love rendering Plotly plots on my notebook pages... so much so that I want to use an `.ipynb` file as my homepage. Is this possible?

I tried the following:
* In `conf.py` setting `master_doc=contents` + renaming 'index.rst' to `contents.rst`
* Making `home.ipynb` the first item in the toc tree instead of 'index'/ 'self'.

The result is the the first item in the toc tree is home.ipynb, but the home and logo buttons still navigate to index.py

```
Name: nbsphinx
Version: 0.8.0

Name: Sphinx
Version: 3.3.1
```

**Comment by mgeier** [comment]
If you want your `index.html` to be generated from a notebook, just use `index.ipynb` instead of `index.rst`.

See also https://nbsphinx.readthedocs.io/en/0.8.0/usage.html#Sphinx-Setup:

> Alternatively, you can delete the file `index.rst` and replace it with your own notebook called `index.ipynb` which will serve as main page. In this case you can create the main [toctree](https://nbsphinx.readthedocs.io/en/0.8.0/subdir/toctree.html) in `index.ipynb`.

**Comment by LayneSadler** [comment]
Thank you. Now I remember reading that paragraph last week! Overlooked it.
