### ISSUE TITLE
footcite support

### ISSUE THREAD

**Issue by clonker** [spatialaudio/nbsphinx#535]
Hi there,
thank you for the great tool you got going on here! I have a request and would also be willing to contribute regarding that if it is of any interest to you.
I am quite heavily using citations inside notebooks (via `<cite data-cite=...>[..]</cite>`) but since I keep my bibliographies separate on a per-document basis, this means creating a unique label prefix for each document. In recent versions sphinxcontrib-bibtex introduced "footbibliographies", where instead of using the global sphinx referencing system, footnotes are used and thus all bibliographies are separate, no more unique labels for me, yay - at least in `rst` (or derivative) documents.
Now I think all that needs to be done is to add an option to the `CitationParser` for it to also handle `data-footcite` attributes.

What do you guys think? Thanks!
Moritz

**Comment by mgeier** [comment]
Sure, that sounds like a great idea, I'm looking forward to a pull request!

**Comment by clonker** [comment]
implemented in PR #536
