### ISSUE TITLE
failing to parse long lines with docutils 0.17

### ISSUE THREAD

**Issue by phildong** [spatialaudio/nbsphinx#549]
My notebooks contains outputs with embed javascripts that's super long. Before `nbsphinx` was happy to convert them. But after I update my build environment today I get the following warnings:

```
xxx.ipynb:: WARNING: Line xxx exceeds the line-length-limit.
```

which is immediately followed by

```
xxx.ipynb:1: WARNING: Each notebook should have at least one section title
```

and eventually this lead to all my notebook not included in the resulting html build since titles are missing.

I can confirm this can be fixed by `pip install docutils==0.16`, but thought it's worth raising it here in case anyone else came across the same issue.

**Comment by mgeier** [comment]
Thanks for the report!

There seems to be a new option in `docutils` 0.17: https://docutils.sourceforge.io/docs/user/config.html#line-length-limit

I don't know yet how to handle this.

Any ideas?

**Comment by skairunner** [comment]
It seems like the docutils project needs to have an option to entirely disable this line length limit.

**Comment by matteobachetti** [comment]
FYI, not knowing about this open Issue here I just filed a bug report to docutils: https://sourceforge.net/p/docutils/bugs/416/

**Comment by grubert** [comment]
did anyone try to raise the line length ?

**Comment by mgeier** [comment]
I've just created #552 which hopefully fixes this issue.
