### ISSUE TITLE
Works locally; fails online: nbsphinx addition

### ISSUE THREAD

**Issue by MichaelHopwood** [spatialaudio/nbsphinx#566]
## Details

* GitHub: https://github.com/tgunda/pvOps
* Docs: https://pvops.readthedocs.io/en/latest/

## Expected Result

In the last few commits, I embedded jupyter notebooks with `nbsphinx` and I added a `whatsnew` page. This works locally. 

![expected1](https://user-images.githubusercontent.com/37667642/118299794-336d2700-b4af-11eb-9d17-cff930ee2a3c.PNG)

![expected2](https://user-images.githubusercontent.com/37667642/118299809-3831db00-b4af-11eb-8bbe-8b8b190ca6a5.PNG)

## Actual Result

Neither of these new additions are showing on the deployed website.

I assume it has to do with the **dependencies**. I already tried adding a docs/requirements.txt file to include nbsphinx and other.

Thanks for any help in advance!

**Comment by mgeier** [comment]
Did you have a look at the "builds" page?

https://readthedocs.org/projects/pvops/builds/

**Comment by mgeier** [comment]
Something like this should do the trick: https://github.com/tgunda/pvOps/pull/24.

**Comment by MichaelHopwood** [comment]
Thanks for contributing. I ended up pulling this into master, but it looks like the issue persists. Any ideas?

**Comment by MichaelHopwood** [comment]
Fixed by adding more dependencies. Thanks for sharing the tip about the build page!
