### ISSUE TITLE
errors loading plotly graphs with latex

### ISSUE THREAD

**Issue by atharva-2001** [spatialaudio/nbsphinx#572]
I am trying to plot Plotly graphs inside sphinx documentation, but it seems MathJax is causing some issues. 
In the documentation, MathJax v3 is being loaded, which causes errors because `MathJax.hub` doesn't exist anymore. 

![image](https://user-images.githubusercontent.com/55894364/119848110-2d545d00-bf29-11eb-8244-4426cae036a2.png)

MathJax v3 should work with plotly because 
```javascript
window.PlotlyConfig = {MathJaxConfig: 'local'};
```
is also present in [the documentation](https://tardis-sn.github.io/tardis/using/visualization/sdec_plot.html) 
([see here as well please](https://github.com/plotly/plotly.js/issues/4563#issuecomment-647047186))

However, if I set `nbsphinx_assume_equations = False` in `conf.py` and remove Latex in cells, I am able to [see the figure](https://atharva-2001.github.io/tardis/branch/revert_sdec_labels_fix_docs/using/visualization/sdec_plot.html), because MathJax is no longer loaded.

![image](https://user-images.githubusercontent.com/55894364/119850611-55dd5680-bf2b-11eb-9ee7-f8453265613a.png)

Could someone please tell me how to solve this?

**Comment by mgeier** [comment]
Can you please provide a minimal reproducible example?

**Comment by atharva-2001** [comment]
Sure, with `nbsphinx_assume_equations = False` in `conf.py`: 
[latex in labels and cells](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples/using/visualization/plotly_latex_cell.html)
[latex only in labels](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples/using/visualization/plotly_latex_no_cell.html)
[no latex at all](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples/using/visualization/plotly_no_latex.html)
see the `conf.py` file used to make these [here](https://github.com/atharva-2001/tardis/blob/sdec_refix_examples/docs/conf.py)

Without any changes in conf.py (`nbsphinx_assume_equations = True`, default value)
[latex in labels and cells](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples_nae_true/using/visualization/plotly_latex_cell.html)
[labels only in latex](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples_nae_true/using/visualization/plotly_latex_no_cell.html)
[no latex at all](https://atharva-2001.github.io/tardis/branch/sdec_refix_examples_nae_true/using/visualization/plotly_no_latex.html)
see the `conf.py` file used to make these [here](https://github.com/atharva-2001/tardis/blob/sdec_refix_examples_nae_true/docs/conf.py)

**Comment by mgeier** [comment]
Thanks for the examples. The aren't really minimal, though.

**Comment by atharva-2001** [comment]
Any updates on this? @mgeier

**Comment by mgeier** [comment]
Not from my side. I'm waiting for a minimal example for me to reproduce and investigate the problem.

**Comment by atharva-2001** [comment]
Could you please check if this works?
[index.html ](https://rawcdn.githack.com/atharva-2001/nbsphinx-test/9ce4d43eb779310b44ff047f274a1471cdbdf320/assume_equations_false/build/html/index.html) with links to files built with `nbsphinx_assume_equations = False` in `conf.py`
[index.html ](https://rawcdn.githack.com/atharva-2001/nbsphinx-test/9ce4d43eb779310b44ff047f274a1471cdbdf320/assume_equations_true/build/html/index.html) with links to files built with `nbsphinx_assume_equations = True` in `conf.py`
[link](https://github.com/atharva-2001/nbsphinx-test) to the repository
I was not sure what was needed, please let me know if I can do anything more.

**Comment by mgeier** [comment]
Thanks, this is still more complicated than necessary, but I can work with it!

IMHO, this should just work regardless of the value of `nbsphinx_assume_equations`.

The problem (or rather one of the problems) seems to be that plotly inserts this code into the HTML page:

```js
        if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
```

... and Sphinx defines `window.MathJax` because `nbsphinx` sets some default values for `mathjax3_config`.
Anyone who uses `mathjax3_config` will have the same problem, even if they don't use `nbsphinx`.

You should make another minimal example without `nbsphinx` that uses `mathjax3_config`, for example

```python
mathjax3_config = {'tex' = {'processEscapes': True}}
```

If this causes the same error (which I think it does), you can create an issue at the plotly issue tracker.
Once that is fixed, you can try it with `nbsphinx` again and we can continue here.

**Comment by mgeier** [comment]
In the meantime, you can work around this problem by either downgrading Sphinx to below version 4 or by manually switching to MathJax 2 like this:

```python
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
mathjax2_config = {
    'tex2jax': {
        'inlineMath': [['$', '$'], ['\\(', '\\)']],
        'processEscapes': True,
        'ignoreClass': 'document',
        'processClass': 'math|output_area',
    }
}
```

**Comment by atharva-2001** [comment]
Thank you very much! I will make an issue in plotly soon.

**Comment by mgeier** [comment]
In the meantime, https://github.com/plotly/plotly.js/pull/6073 has been merged.

Maybe it works now with MathJax 3?
