### ISSUE TITLE
Bullet points are not rendering in furo theme.

### ISSUE THREAD

**Issue by kolibril13** [spatialaudio/nbsphinx#574]
In my notebook I have bullet points, that are getting rendered to bullet points locally, but not in the Spinx build with nbsphinx.
Rendered:
https://flyingframes.readthedocs.io/en/latest/ch1.html
notebook in GitHub:
https://github.com/kolibril13/flyingframes/blob/main/docs/source/ch1.ipynb
However, on the nbsphinx website, it is shown properly:
https://nbsphinx.readthedocs.io/en/furo-theme/markdown-cells.html
Any ideas what I can do? It does not bother me a lot, so if it requires big workarounds, I am fine to have bullet points only be displayed by stars.

**Comment by mgeier** [comment]
Did you try removing the trailing double-spaces?

**Comment by kolibril13** [comment]
Thanks for your reply!
I have just removed the trailing double-spaces, and now it looks like this:
It actually became worse 😄 
![image](https://user-images.githubusercontent.com/44469195/122285588-38c6f280-ceef-11eb-8015-2038eea02eef.png)
https://flyingframes.readthedocs.io/en/latest/ch1.html (link from 16.6.2021)

**Comment by mgeier** [comment]
There is still a double space in the line before the list.

**Comment by kolibril13** [comment]
ok, now I removed all spaces, but the problem is still there:
https://flyingframes.readthedocs.io/en/latest/ch1.html

**Comment by mgeier** [comment]
Hmmm, what about adding a blank line before the list?

The problem is that JupyterLab (and the classic Notebook app) uses a different Markdown parser than `nbsphinx` (which currently uses Pandoc). So there might be slight differences in how Markdown features are interpreted.

**Comment by kolibril13** [comment]
Great! 
Thanks a lot, that solved my problem! :)
