### ISSUE TITLE
Plotly graphs are not rendering

### ISSUE THREAD

**Issue by aleixalcacer** [spatialaudio/nbsphinx#587]
I'm having issues rendering Plotly graphs when nbsphinx is used. Thus, I have created a minimal project that reproduces the issue: https://github.com/aleixalcacer/sphinx-plotly

As can be seen in the [html rendering](https://aleixalcacer.github.io/sphinx-plotly), the plotly figures are not displayed.

![Captura de pantalla 2021-07-23 a las 9 47 16](https://user-images.githubusercontent.com/29116747/126752184-31ff7276-a87a-4a61-996a-57ebf3d0352b.png)

Do you have any idea what it can be?

**Comment by mgeier** [comment]
It looks like Plotly only supports MathJax version 2, but Sphinx and `nbsphinx` have switched to version 3 recently.

See https://github.com/spatialaudio/nbsphinx/issues/572#issuecomment-853389268 for how to switch back to version 2.

**Comment by aleixalcacer** [comment]
Thanks a lot. That has solved my issue. :)
