### ISSUE TITLE
Documenting nbsphinx_assume_equations

### ISSUE THREAD

**Issue by diego-plan9** [spatialaudio/nbsphinx#603]
Would it be possible to add `nbsphinx_assume_equations` to the documentation? I found the (useful!) option recently a bit by chance - when trying to look it up for more details using the `0.8.7` documentation, I could [only] find a reference in the changelog. 

The changelog entry was still enough, though (and looking at the related PR and an issue mentioning the option clarified its usage even more) - it's mostly for making it slightly easier to find.

[only]: https://nbsphinx.readthedocs.io/en/0.8.7/search.html?q=nbsphinx_assume_equations

**Comment by mgeier** [comment]
Sure, it would be good to add this to the documentation! Do you want to make a PR?

**Comment by diego-plan9** [comment]
Thanks for the quick reply! Yes, I can give it a try :+1:
