### ISSUE TITLE
Bug: Copy Button is Visible for Cellcounter

### ISSUE THREAD

**Issue by kolibril13** [spatialaudio/nbsphinx#607]
I think it is more a bug than a feature, the sphinx-copybutton shows up on the cell itself (as intended), but also at the cell counter:
Alabaster theme:
![image](https://user-images.githubusercontent.com/44469195/139592270-c3d1bf4d-3fac-4474-9227-623a634cb0ad.png)

Furo theme:
![image](https://user-images.githubusercontent.com/44469195/139592289-99549491-263d-4275-8e40-743ab26a36cd.png)

**Comment by mgeier** [comment]
This should already be handled:

https://github.com/spatialaudio/nbsphinx/blob/8bd255757ade0d072e5e13c9da706e002d6fa050/src/nbsphinx.py#L646-L649

But maybe the CSS names in `sphinx-copybutton` have changed?

**Comment by kolibril13** [comment]
This is the css file I found in one of my projects build folder:
![image](https://user-images.githubusercontent.com/44469195/143049333-dc5d776d-2e15-4ee8-a15d-26cfb8839133.png)

**Comment by mgeier** [comment]
#610 should fix this. Can you please check if it works for you?
