### ISSUE TITLE
Failed to build documentation following steps in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by ohrely** [spatialaudio/nbsphinx#617]
I created a fresh conda environment, installed python, then attempted to follow the steps in https://github.com/spatialaudio/nbsphinx/blob/master/CONTRIBUTING.rst#building-the-documentation .  Requirements installation went smoothly but the second step, `python3 setup.py build_sphinx`, failed with the following error:

> Notebook error:
> PandocMissing in a-markdown-file.md:
> Pandoc wasn't found.
> Please check that pandoc is installed:
> https://pandoc.org/installing.html

I was able to get past this with a `conda install pandoc`, so am not currently blocked, but this may trip up future contributors.  Hope this helps, thanks for the thorough instructions!

**Comment by mgeier** [comment]
Thanks for the report!

I was assuming that people who want a "development" installation already have a working "normal" installation.

Apparently, this assumption is not good.

I've created #618, does this clarify the situation?
