### ISSUE TITLE
Notebook gallery without listing in table of contents?

### ISSUE THREAD

**Issue by hakonanes** [spatialaudio/nbsphinx#647]
Can I create a notebook gallery, say, on the index page, without the notebooks listed in the table of contents? I assume no, since the `nbgallery` directive takes the same parameters as the `toctree` directive.

**Comment by mgeier** [comment]
Did you try the `hidden` flag?

See https://nbsphinx.readthedocs.io/en/0.8.8/subdir/toctree.html.

To also remove it from the sidebar, I had to set `globaltoc_includehidden` to `False`, even though that is supposed to be the default value (see https://www.sphinx-doc.org/en/master/usage/theming.html?highlight=globaltoc_includehidden%20#builtin-themes).

**Comment by hakonanes** [comment]
Thanks for the quick reply!

I should note that I'm including `nbgallery` directives in a `index.rst` file, and that I'm using the Furo theme.

I tried the `hidden` flag, as in

```
.. nbgallery::
    :hidden:
    
    my_notebook.ipynb
```

but the notebook is still listed in the sidebar. I didn't try `nbsphinx-toctree` since it's gallery notebooks I don't want listed in the sidebar, and it seems to me that `nbsphinx-toctree` is a regular `toctree`. Is `globaltoc_includehidden` set to `False` in the `html_theme_options` dictionary in `conf.py`?

While it would be nice if I could include a notebook gallery without the notebooks listed in the sidebar, it isn't crucial. I'm very happy with `nbsphinx`, and I believe I can get a good documentation even with all notebooks listed in the sidebar. Feel free to close this if you consider it an edge case or otherwise.

**Comment by hakonanes** [comment]
Thanks for clarifying.

> but maybe Furo doesn't support it.

I believe you're right, I cannot find the option in the current [customization documentation](https://pradyunsg.me/furo/search/?q=globaltoc&check_keywords=yes&area=default). It seems like [templating](https://pradyunsg.me/furo/customisation/sidebar/#changing-sidebar-elements) might be an option, but I don't have the time to look further at the moment.

**Comment by mgeier** [comment]
You can try it with another theme, e.g. with one of the built-in themes like `classic`.

If it works there, you can close this issue and create a new issue for the Furo theme.

I don't think that https://pradyunsg.me/furo/customisation/sidebar/#changing-sidebar-elements helps, since  `sidebar/navigation.html` is a custom template provided by Furo. The one provided by Sphinx would be called `globaltoc.html`, but I guess that's not compatible with Furo?

See also https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_sidebars

**Comment by hakonanes** [comment]
> The one provided by Sphinx would be called globaltoc.html, but I guess that's not compatible with Furo?

Yes, this template is [explicitly not supported](https://github.com/pradyunsg/furo/blob/main/src/furo/theme/furo/globaltoc.html).

I'll try with a built-in theme, thanks.

**Comment by mgeier** [comment]
@hakonanes Did it work with a different theme?

**Comment by hakonanes** [comment]
Sorry for the late reply: I abandoned this approach and decided to stick to the current behaviour.

Please close this issue at your convenience, @mgeier.
