### ISSUE TITLE
Matplotlib Figures and stdout rendered as blank cells in html

### ISSUE THREAD

**Issue by lee-t** [spatialaudio/nbsphinx#652]
Unsure how to provide a minimal example for this so I'll just link to the respective files in my [repo](https://github.com/ccb-hms/BioPlexPy/tree/main/docs). I have a [notebook](https://github.com/ccb-hms/BioPlexPy/blob/main/docs/BioPlex_Examples.ipynb) that's being used to serve as documentation and it contains cells with pandas DataFrame, stdout from `print() `and matplotlib figures. I've configured sphinx to use nbsphinx as an extension, it parses the html. The resulting [document](https://bioplexpy.readthedocs.io/en/latest/BioPlex_Examples.html#Example-2:-TFIIH-Complex-(using-wrapper-function)) renders pandas DF and cell outputs but nothing from` print()` nor any of the matplotlib figures from` plt.show()` are rendered. For some reason, the images are saved in _images but the html page is built with the respective images linked to an empty container.  None of the warnings from sphinx during make html tell me what is happening. Changing `c.InlineBackend.figure_formats = {'png'}` to svg does not resolve this issue and it does not matter if its specified in the conf.py, ipython_kernel_config.py, or the notebook itself (%config InlineBackend.figure_formats = ['png']).

I decided against making an issue with nbconvert because I've tried converting this into .rst and the figures do render but the pandas DF tables are poorly formatted, one of the reasons I'm using nbsphinx was because it automatically formats DF properly in html.

**Comment by mgeier** [comment]
This seems to be because of your custom CSS:

    display(HTML("<style>.container { width:100% !important; }</style>"))

Can you try removing this?

**Comment by lee-t** [comment]
I have tried removing this, the same issue persists.

**Comment by lee-t** [comment]
I've added` nbsphinx_execute = 'always'` to conf.py, the plots and output now render in html. Seems that the saved output in the ipynb are not parsed unless the notebook is executed, not sure if this is intended behavior but between this and the custom CSS I think this issue is solved for my case at least. I don't see anyone else having this issue so I'm closing for now. Thank you Matthias.

**Comment by mgeier** [comment]
Good to know that it works now!

> Seems that the saved output in the ipynb are not parsed unless the notebook is executed, not sure if this is intended behavior

Yes, this is intended. If the code cell outputs are stored in the notebook (like in your case), the default is to not execute it, see https://nbsphinx.readthedocs.io/en/0.8.9/executing-notebooks.html.

I normally remove the outputs before committing the notebooks to Git, then the notebooks are automatically executed.
