### ISSUE TITLE
Breakage at Sphinx 5.1.0 for PDF via LaTeX (undefined \spx@fcolorbox)

### ISSUE THREAD

**Issue by jfbu** [spatialaudio/nbsphinx#656]
Following instructions of CONTRIBUTING.rst to build the documentation (as a test) in LaTeX then PDF, I get this build breaking error from `make nbsphinx.pdf` in the latex build directory:
```
[30]
! Undefined control sequence.
\nbsphinxfcolorbox ->\spx@fcolorbox 
                                    {nbsphinx-code-border}{white}
l.2902 \begin{nbsphinxfancyoutput}
```
This happens with Sphinx at least at 5.1.0.

Indeed some dubious maintainer at Sphinx (myself ;-) ) has renamed internal macro `\spx@fcolorbox` (and changed its interface a bit) at 5.1.0....

Sorry for the breakage, I will provide a PR at some point, hopefully today if time allows, or at any rate tomorrow, to refactor `nbsphinxfancyoutput` in a way not using internal Sphinx macros and keeping exact same behaviour otherwise.

see PR #657

**Comment by mgeier** [comment]
Thanks for checking this!
