### ISSUE TITLE
Pass through HTMLExporter.html_manager_semver_range config to nbconvert

### ISSUE THREAD

**Issue by ohrely** [spatialaudio/nbsphinx#672]
@jnnamchi and I are running into an issue introduced by a recent release of @jupyter-widgets/html-manager (1.0.1) that could be circumvented by [the approach described in this comment on an ipydatagrid issue](https://github.com/bloomberg/ipydatagrid/issues/338#issuecomment-1238012835):

> try running nbconvert with the option --HTMLExporter.html_manager_semver_range="0.20.2"

As far as we can tell, nbconvert will only respect a pinned version of html-manager if it's passed as a config in the nbconvert call, which for us is abstracted by nbsphinx.  It looks like there are already a few precedents for passing through config values from nbsphinx to nbconvert in https://github.com/spatialaudio/nbsphinx/blob/master/src/nbsphinx.py; is there any reason not to take that same approach for exposing this config?

**Comment by mgeier** [comment]
> is there any reason not to take that same approach for exposing this config?

I don't think so.

But maybe that's not even necessary. Did you try passing the option via `nbsphinx_execute_arguments`?

https://nbsphinx.readthedocs.io/en/latest/configuring-kernels.html#Kernel-Arguments

**Comment by Jnnamchi** [comment]
Our config has the `nbsphinx_execute = 'never'` setting in conf.py, so nbsphinx_execute_arguments will not have an effect on the html that gets produced. 

So we did still try to run nbsphinx build with nbsphinx_execute_arguments just in case but as expected it had no effect.

We will try to implement @ohrely 's suggestion and get a PR out next week for review. Until then any other ideas are welcome!

Thanks!

**Comment by mgeier** [comment]
Sorry for leading you on a wrong path, I didn't ready your description very carefully.

Now that it read it somewhat more carefully, I'm starting to understand that this is about the version of the JavaScript that is inserted to make widgets work, right?

I guess you want to set `nbsphinx_widgets_path` in your `conf.py`?

https://nbsphinx.readthedocs.io/en/0.8.9/usage.html#nbsphinx_widgets_path

**Comment by mgeier** [comment]
Alternatively, it might work by downgrading `ipywidgets`, which is the source for the default URL.

**Comment by mgeier** [comment]
BTW, `nbconvert` is only used for executing the notebooks, not for generating the HTML, so setting the parameter `--HTMLExporter.html_manager_semver_range` wouldn't have any effect.

**Comment by Jnnamchi** [comment]
@mgeier nbsphinx_widgets_path turned out to be the solution for us. We set it to the following and all the built html pages call that path. Thanks for the note! We can close this issue.
