### ISSUE TITLE
LaTeX: get rid of rounded corners from Sphinx 6

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#684]
The boxes for code cells should never have rounded corners.

I know that I can add `pre_border-radius=0px` to `latex_elements.sphinxsetup`, but this shouldn't be a user setting in the first place.

The boxes should also have all 4 borders when they are broken between pages.

@jfbu Do you have an idea how to achieve this?

**Comment by jfbu** [comment]
> The boxes should also have all 4 borders when they are broken between pages.

Hi, use ``pre_box-decoration-break=clone`` in ``latex_elements.sphinxsetup``

**Comment by jfbu** [comment]
> I know that I can add `pre_border-radius=0px` to `latex_elements.sphinxsetup`, but this shouldn't be a user setting in the first place.

Yes use ``pre_border-radius=0px`` to revert to pre 6.0.0 default

**Comment by mgeier** [comment]
Thanks for the quick answer!

I've created #685 as a possible way forward.

Would this be the correct solution?
