### ISSUE TITLE
docs/bibliography depends on docutils>0.19.0

### ISSUE THREAD

**Issue by 2bndy5** [spatialaudio/nbsphinx#735]
https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/doc/requirements.txt#L11-L12

docutils v0.19 is released, so I think this can be removed or changed to 

```
docutils>=0.19
```

This would also improve dev workflows for local environments that don't have `svn` installed.

PS - This specification also may limit what version of Sphinx can be used (`>=5.0` IIRC), but thankfully this is only stated for the docs and not the lib itself.

**Comment by 2bndy5** [comment]
git blame references #701

**Comment by mgeier** [comment]
This is a strict "greater than": `docutils > 0.19.0`

The problem is still present in 0.19.0 and there hasn't been a new release yet.

> thankfully this is only stated for the docs and not the lib itself

Yes, because this is only a problem when a bibliography is needed (which is the case in the docs).

**Comment by 2bndy5** [comment]
I'm leaving this open for tracking, but you can close this if you want (you seem to be on top of it).

**Comment by mgeier** [comment]
If all goes well, a new version of `docutils` will be released next week. After that, I will remove the work-around.

**Comment by mgeier** [comment]
I have removed the work-around in #742.
