### ISSUE TITLE
allow exception in docs' bash input (for Windows devs' local env)

### ISSUE THREAD

**Issue by 2bndy5** [spatialaudio/nbsphinx#736]
In testing my changes to the lib, I found it more convenient to add the metadata tag `raises-exception` for the input in [code-cells.ipynb](https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/doc/code-cells.ipynb):
```bash
%%bash
for i in 1 2 3
do
    echo $i
done
```

Since the CI must be using Linux environments, I doubt this would be detrimental to any deployments.

**Comment by mgeier** [comment]
I don't think we actually need this, see #739.

**Comment by 2bndy5** [comment]
It is needed to build the current docs on Windows. Using WSL is an alternative approach, but it is significantly and noticably slower to execute. Not to mention, its more difficult to install arch-specific dependencies for WSL.

Changes in #739 should work fine as well.

**Comment by mgeier** [comment]
OK, thanks, I've merged #739.
