### ISSUE TITLE
Not compatible with the latest `pandoc` version

### ISSUE THREAD

**Issue by munechika-koyo** [spatialaudio/nbsphinx#750]
The latest `pandoc` version is 3.1.3, which is not compatible with the latest `nbsphinx`.
So, it should adapt to the `pandoc` over v3.0.0.

**Comment by mgeier** [comment]
> is not compatible with the latest `nbsphinx`.

Can you please elaborate?

I remember reading about an upper version bound enforced by `nbconvert`:

https://github.com/jupyter/nbconvert/issues/1996
https://github.com/jupyter/nbconvert/pull/1997

Did you try the latest `nbconvert`?

**Comment by munechika-koyo** [comment]
I am sorry that I did not attach any log.
I saw the following warning msg.
```bash
/home/koyo/.conda/envs/cherab-lhd-dev/lib/python3.11/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (3.1.3).
Your version must be at least (1.12.1) but less than (3.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
```
Anyway, my `nbconvert` version was 7.2 somehow, so updating it to 7.6 resolved this issue.
Thank you for your advice:)
