### ISSUE TITLE
xelatex support

### ISSUE THREAD

**Issue by ianhbell** [spatialaudio/nbsphinx#763]
Hello! nbsphinx is awesome, and I am happily using it in a few projects. I have a small issue with pdf generation though. I have some unicode characters in my notebooks, and I therefore need to build with xelatex. I tried switching my engine to xelatex in my conf.py with:

```
latex_engine = 'xelatex' 
```
and built. When I do so, xelatex has a lot of complaints about missing commands, along the lines of:
```
! Undefined control sequence.
\nbsphinxfcolorbox ->\spx@fcolorbox 
                                    {nbsphinx-code-border}{white}
l.2982 \begin{nbsphinxfancyoutput}
                                  
? 
! Undefined control sequence.
\nbsphinxfcolorbox ->\spx@fcolorbox 
                                    {nbsphinx-code-border}{white}
l.2990 \end{nbsphinxfancyoutput}
                                
? 
! Undefined control sequence.
\nbsphinxfcolorbox ->\spx@fcolorbox 
                                    {nbsphinx-code-border}{white}
l.2990 \end{nbsphinxfancyoutput}
```

Any idea how to fix the nbsphinx-converted files to build properly with xelatex?

**Comment by mgeier** [comment]
Can you please provide a minimal reproducible example?
I just tried it with the `nbsphinx` docs and it seems to work fine with no errors.

**Comment by ianhbell** [comment]
Yes, I will work on a MRE

**Comment by ianhbell** [comment]
I can't reproduce the problem in a smaller MRE. Let me see if I can find a way to remove things from my rather bulky code to get down to something that yields the same error. We can close for now until I can find the time to re-open
