### ISSUE TITLE
How to link to a notebook from another file ?

### ISSUE THREAD

**Issue by cottephi** [spatialaudio/nbsphinx#764]
Hello everyone,
I am trying to do something for which I did not find any documentation :

 * I have an example python file that I put in a gallery using [sphinx-gallery](https://sphinx-gallery.github.io/stable/getting_started.html#create-simple-gallery), which contains docstring.
 * I have a notebook in another gallery created using nbsphinx.

Note that both the file and the notebook and displayed correctly in the resulting documentation.

And I want to add a **reference to the notebook in the python file's docstring**.

First, I thought of doing something like that in my **examples.rst** file :

```rst
.. _examples:

Examples
========

Notebooks
---------

.. nbgallery::
   :caption: See some examples in notebooks :

   .. _mynb:
                    <-- tried also without the blank line, same result
   examples/notebooks/mynb.ipynb
```

and this in my python file :

```python
"""
See Also:
    :ref:`mynb`
"""
```

But that does not work, compilation warns :
*/my/project/path/docs/source/auto_examples/imports/myfile.rst:27: WARNING: undefined label: 'mynb'*

Any idea on how I could achieve this ?

**Comment by mgeier** [comment]
The [`nbgallery` directive](https://nbsphinx.readthedocs.io/en/0.9.3/a-normal-rst-file.html#thumbnail-galleries) is based on the [`toctree` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree), which expects a list of document names. Putting a link anchor in there is not supported, and it really doesn't make too much sense, anyway. I guess you want to link to the given document, not to the position where the link to the document will appear, right?

As for how to link to a notebook from reST, this is documented here: https://nbsphinx.readthedocs.io/en/0.9.3/a-normal-rst-file.html#links-to-notebooks-and-other-sphinx-source-files.
