### ISSUE TITLE
WARNING: toctree glob pattern '*.ipynb' didn't match any documents

### ISSUE THREAD

**Issue by riyajatar93** [spatialaudio/nbsphinx#765]
i have my all notebooks inside a folder called Notebook which outside of source dir, now i want to add those all notebooks.
this is what i tried.

`NOTEBOOKS
-------------------
.. toctree::
   :maxdepth: 2
   :glob:
   ../Notebook/*.ipynb`

getting this 
WARNING: toctree glob pattern '*.ipynb' didn't match any documents

**Comment by mgeier** [comment]
https://github.com/vidartf/nbsphinx-link
