### ISSUE TITLE
nbsphinx PDF don't render Ploty Plot

### ISSUE THREAD

**Issue by gbullido** [spatialaudio/nbsphinx#770]
When making "make latexpdf" the PDF is created well but the cells where there is a plotly plot is not displayed. Places "Data type cannot be displayed: application/vnd.plotly.v1+json"

How can I fix this?

**Comment by mgeier** [comment]
AFAIK, plotly doesn't provide an output in LaTeX/PDF/PNG, nor SVG format. All those would be supported in `nbsphinx` with the `latexpdf` builder. But plotly provides some HTML with some JavaScript, which is not supported.

> How can I fix this?

I'm not sure, a few things come to mind:

* use a different plotting tool that supports one of the above-mentioned output formats
* implement plotly support in `nbsphinx`
* convert your notebooks to PDF with `nbconvert`'s `webpdf` output: https://nbconvert.readthedocs.io/en/latest/usage.html#webpdf
* try if it happens to work with https://jupyterbook.org/ or https://myst-nb.readthedocs.io/ or any of the other tools mentioned at https://nbsphinx.readthedocs.io/links.html

**Comment by gbullido** [comment]
@mgeier Just convert my graphics to MatplotLib and everything is working fine now.

**Comment by gbullido** [comment]
@mgeier Just convert my graphics to MatplotLib and everything is working fine now.

Thanks.
