### ISSUE TITLE
Error on cells using progress bar (tqdm)

### ISSUE THREAD

**Issue by ThibaultFy** [spatialaudio/nbsphinx#776]
Hello, I got the error 

> `ERROR: Content block expected for the "raw" directive; none found.`

on my cells using a progress bar (tqdm for instance). It appears when upgrading to Sphinx 7.2.6.

**Comment by arjunsavel** [comment]
I'm also seeing this in my logs: https://readthedocs.org/api/v2/build/23454115.txt

**Comment by mgeier** [comment]
This has been reported at https://github.com/jupyter/nbconvert/issues/2092.

This should probably be fixed in `nbconvert`, but I'm not sure if it should also be worked-around in `nbsphinx`.

Any suggestions?

Any volunteers?

In the meantime, pinning `nbconvert < 7.14` should avoid the problem.

**Comment by ThibaultFy** [comment]
Thanks for pointing the nbconvert issue. 

I'll try with nbconvert 7.13. 
For now, I just stopped running my notebooks (`nbsphinx_execute = "never"`) waiting for one of these issue to be fixed 🤞 .

**Comment by ThibaultFy** [comment]
Pinning nbconvert to 7.13 fixed it. Should I close this issue ?

**Comment by mgeier** [comment]
I think this should stay open until there is a real fix. Pinning `nbconvert` isn't really a long-term solution.

**Comment by mgeier** [comment]
I suggested a fix to `nbconvert`: https://github.com/jupyter/nbconvert/pull/2142

**Comment by mgeier** [comment]
`nbconvert` v7.16.4 has just been released and it should fix this problem.

@ThibaultFy @arjunsavel Can you please check if that works for you?

**Comment by mgeier** [comment]
I assume this works now. If not, please let me know!
