### ISSUE TITLE
LaTeX build breaks with Sphinx version 1.5

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/nbsphinx#78]
That's because I'm assuming that the whole `sphinxVerbatim` environment is contained in a single list element in `self.body` here: https://github.com/spatialaudio/nbsphinx/blob/4f50816d1252cecc28e3472a99c02eb0a3706704/nbsphinx.py#L1162

Sadly, https://github.com/sphinx-doc/sphinx/pull/3022 broke that assumption.

**Comment by mgeier** [comment]
https://github.com/sphinx-doc/sphinx/issues/3224 will hopefully fix this, and #79 will disable Sphinx 1.5.

**Comment by michaelpacer** [comment]
Ok, sphinx 1.5.1 does not fix this(I think); but I can't be sure because I can't locally reproduce this issue in any case :/.

**Comment by mgeier** [comment]
Does #85 fix this?

**Comment by michaelpacer** [comment]
I can confirm, this fixes the error on both 1.5.0 and 1.5.1 (with docutils 1.12.0).
