### ISSUE TITLE
assertion error in `depart_code_latex`

### ISSUE THREAD

**Issue by SylvainCorlay** [spatialaudio/nbsphinx#80]
The assertion `assert lines[0] == ''` fails for the ipywidgets documentation (and has been failing for some time).

Instrumenting the code locally shows that `lines` is equal to `['}', '']`.

```
Exception occurred:
  File "/Users/scorlay/jupyter/spatialaudio/nbsphinx/nbsphinx.py", line 1156, in depart_code_latex
    assert lines[0] == ''
```

**Comment by mgeier** [comment]
Duplicate of #78.

**Comment by mgeier** [comment]
Does #85 fix this?
