### ISSUE TITLE
nbsphinx breaks the raw directive

### ISSUE THREAD

**Issue by adosar** [spatialaudio/nbsphinx#800]
I am using Sphinx to build the documentation for my package, and inside an `.rst` file I have the following content:

```rst
.. raw:: html
    :file: images/plotly.html
```
which renders an interactive Plotly figure. Eveyrthing works fine until I add `'nbsphinx'` in the `extensions` (in `conf.py`).

**Comment by mgeier** [comment]
Can you please provide a minimal reproducible example?

**Comment by mgeier** [comment]
As a quick stab in the dark, you can also try to set `nbsphinx_requirejs_path` to the empty string.

https://nbsphinx.readthedocs.io/en/0.9.4/configuration.html#nbsphinx_requirejs_path

**Comment by mgeier** [comment]
@adosar Any news on this?

**Comment by mgeier** [comment]
@adosar Did you try my suggestion from https://github.com/spatialaudio/nbsphinx/issues/800#issuecomment-2179383584?
