### ISSUE TITLE
Sphinx 9 compatibility

### ISSUE THREAD

**Issue by flying-sheep** [spatialaudio/nbsphinx#804]
Trying to build our docs with Sphinx 8, I see:

```
…site-packages/nbsphinx/__init__.py:1345:
  RemovedInSphinx90Warning:
  Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead.
```

The problem is this line apparently:
https://github.com/spatialaudio/nbsphinx/blob/b0b5274d686fa7b66d159e1645634c3ff6959774/src/nbsphinx/__init__.py#L1361

**Comment by mgeier** [comment]
Thanks for the report!

It's a continuous source of work to keep up with Sphinx breaking backwards compatibility ... but this should do it for now: #807.
