### ISSUE TITLE
outdated mathjax path in built html

### ISSUE THREAD

**Issue by fkuehlein** [spatialaudio/nbsphinx#806]
Hi!

When I build my docs using nbsphinx and upload them on our [website](https://www.pik-potsdam.de/~donges/pyunicorn/tutorials/ClimateNetworks.html), LaTeX equations fail to be displayed. I noticed that the html files contain a 

```html
<script defer="defer" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

which might cause the problem as on one hand, `cdn.mathjax.org` has long been [retired](https://www.mathjax.org/cdn-shutting-down/) and on the other, browsers might refuse to load the `http://` resource.

I tried [setting the mathjax path](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax_path) by adding

```python
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
```
to my `conf.py`, but it doesn't change anything. 

Please excuse that I haven't managed to provide a minimal example to reproduce this yet. Also not entirely sure if this is a problem with nbsphinx or sphinx itself. All the more, any help is greatly appreciated :-)

-------
I use:
- python 3.12.2
- sphinx 7.3.7
- nbsphinx 0.9.4

**Comment by mgeier** [comment]
Thanks for reporting this!

`nbsphinx` does some manipulations with the MathJax settings, but it shouldn't touch the URL/path.

Can you please try to create a minimal Sphinx example without `nbsphinx` and see what happens?

If the problem still appears without `nbsphinx`, please report this to https://github.com/sphinx-doc/sphinx/issues.

**Comment by fkuehlein** [comment]
Ooops, I just found that the `mathjax_path` was set to the outdated URL somewhere else in the `conf.py` where I hadn't found it. My bad, thank you anyway for the quick reply!
