### ISSUE TITLE
Maplotlib figures do not render

### ISSUE THREAD

**Issue by par2** [spatialaudio/nbsphinx#9]
After building, it seems my plots for matplotlib are not rendering.  In place of the images are paths to files in the doctrees folder, e.g:

_build%5Cdoctrees%5Cnbsphinx%5Cshowcase_121_1.png

Those images do exist at these paths, but are not being rendered somehow `make html`.  The errors says these files are not readable, which is odd since they are generated from the notebook.  Any thoughts?

**Comment by par2** [comment]
UPDATE:  It appears the mpl output cells do render on readthedocs.  They do not render locally.

**Comment by mgeier** [comment]
This problem only seems to occur on Windows (or it may be related to changes between Sphinx version 1.3.3 and 1.3.4) , see #6.

What OS, what Sphinx version are you using?

**Comment by mgeier** [comment]
I just saw that `'%5C'` means `'\'`, so I assume it's a Windows problem.
I'm trying to find a way to avoid this ...

**Comment by mgeier** [comment]
Can you please check if #10 fixes your problem?

**Comment by par2** [comment]
I wasn't sure how to check this properly, but I went ahead and edited nbsphinx.py in site packages.  Looks like it resolved the issue.  Images now render locally.  Thanks.

**Comment by mgeier** [comment]
Thanks for testing!

I added an explanation how to properly check out and install different Git branches: https://github.com/spatialaudio/nbsphinx/blob/master/CONTRIBUTING.rst
Please let me know if this is helpful to you.

Thanks for the praise, I'm looking forward to further bug reports and suggestions!
