### ISSUE TITLE
NBSphinx builds broken with nbconvert-5.1.1 (TemplateNotFound ... nbsphinx-rst)

### ISSUE THREAD

**Issue by timstaley** [spatialaudio/nbsphinx#93]
Hi folks,

just a heads-up that nbsphinx seems to be incompatible with the latest release of nbconvert, [5.1.1](https://github.com/jupyter/nbconvert/releases/tag/5.1.1). The error looks something like this:

    Notebook error:
    TemplateNotFound in tutorial/01-parsing.ipynb:
    nbsphinx-rst
    Makefile:45: recipe for target 'html' failed

I've not dug into the underlying cause but I'd hazard a guess it's something to do with changes to nbconvert's template handling, cf https://github.com/jupyter/nbconvert/issues/490

A simple workaround is to specify `nbconvert==5.0.0` in the requirements file.

**Comment by michaelpacer** [comment]
An easier fix is to merge https://github.com/spatialaudio/nbsphinx/pull/94 which fixes the issue by getting the file names to match.

**Comment by michaelpacer** [comment]
also trying to fix in nbconvert itself: https://github.com/jupyter/nbconvert/pull/518
