### ISSUE TITLE
Jupyter kernel job ignores conf.py's sys.path 

### ISSUE THREAD

**Issue by jschueller** [spatialaudio/nbsphinx#96]
The job that is run on the kernel to execute each cell is not aware of the settings of `sys.path` that could have been set in the sphinx's `conf.py` file.

In my case, I set an additional `sys.path` in my `conf.py` to be able to load a newly built module in it's build directory (it does not exist on the system)

    sys.path.insert(0, '<build_dir>/openturns')

Then when the jupyter kernel worker runs to execute the cells this setting is not passed and it throws an ImportError which results in a CellExecutionError.

I saw there's an `nbsphinx_execute_arguments` options option to pass kernel options, would it be possible to work around this by passing an option to the kernel that adds my custom dir to `sys.path` ?

**Comment by mgeier** [comment]
Am I understanding correctly that your notebook wouldn't work in the Jupyter Notebook app nor when executed with `nbconvert --execute`?

So why would you expect it to work with `nbsphinx` then?

If you need any path manipulations for running your notebook, you should do them in the notebook.

**Comment by jschueller** [comment]
My notebook is working when my module is installed in the python prefix, ie when an user installs it, but the failure I'm facing is when I'm developing the module and it's being built and not available on the system yet, ie it's not it /usr/lib/pythonxy/site-packages.

**Comment by mgeier** [comment]
I see.

Did you check the check box "Install your project inside a virtualenv using setup.py install" in the "Advanced Settings" on RTD?

If you use `conda`, you should use one of those:

```yaml
python:
  setup_py_install: true
```

```yaml
python:
  pip_install: true
```

See also http://docs.readthedocs.io/en/latest/yaml-config.html.

BTW, with that, your doctests should also work, no need to manipulate the path in `conf.py`.
This is normally only used to find local (i.e. not installed) Sphinx extensions.

**Comment by jschueller** [comment]
I do not build my project inside a virtualenv because it's mainly a C++ project, that provides Python bindings.

**Comment by mgeier** [comment]
But you *could* do it ...?

**Comment by jschueller** [comment]
I could also override PYTHONPATH in the sphinx process so the kernel process inherits it, which is easier.

**Comment by mgeier** [comment]
Sure, this might work.
But why don't you want to install your package on RTD?
This way you could also test if the installation works outside of your local setup, which is an added bonus.

**Comment by jschueller** [comment]
what's RTD ?
We already have continous integration.
Anyways, thanks for your input.

**Comment by mgeier** [comment]
With RTD I mean readthedocs.org. I was assuming you are talking about this, but apparently I was wrong ...

**Comment by jschueller** [comment]
Yes did not mention rtd, I'm trying to build my documentation locally.

**Comment by mgeier** [comment]
OK, I see.
If you build it locally, you can just install your package before that, right?

**Comment by jschueller** [comment]
That's the point of my ticket, it's not meant to be installed in the system right away, but in a temporary build dir.

**Comment by mgeier** [comment]
OK, I see.
Automatically taking `sys.path` from `conf.py` is still the wrong way to solve this.

Does manipulating `$PYTHONPATH` work for you?

**Comment by jschueller** [comment]
yes

**Comment by mgeier** [comment]
OK, great!
