### ISSUE TITLE
TemplateNotFound: nbsphinx-rst

### ISSUE THREAD

**Issue by jacobkolind** [spatialaudio/nbsphinx#97]
I've tried getting started with npsphinx for a couple of hours now, but so far I haven't been able to find the cause behind the following error:

```
(sphinx35) C:\Users\JKO\Documents\sphinx>make.bat html
Running Sphinx v1.5.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] test
Notebook error:
TemplateNotFound in test.ipynb:
nbsphinx-rst
```

I have been following the instructions [here](http://nbsphinx.readthedocs.io/en/0.2.12/usage.html#Sphinx-Setup).

I am running nbsphinx on a Windows 64bit machine inside a clean conda environment created like this:

```
conda create -n sphinx35 pandas sphinx nbsphinx jupyter matplotlib python=3.5
```

Any idea what may be causing this error? I got as far as pulling out all your code into a notebook, and there I got `exporter.from_notebook_node(nb, resources)` to work. This puzzled me, since this is where I thought the loading of the template was done. I haven't done any testing using your `NotebookParser` class, because I wasn't sure how to set up the docutils document correctly.

**Comment by mgeier** [comment]
This looks very much like #93 which was fixed in #95.

Can you please make sure that you use the latest release of `nbsphinx` (version 0.2.13 from a few days ago)?

I'm not responsible for any `conda` package of `nbsphinx`, it may not be up to date.

**Comment by jacobkolind** [comment]
That could very well be it. Conda-forge is at the moment providing version 0.2.11 of the package. An issue has already been raised with the recipe maintainer to bump the version, conda-forge/nbsphinx-feedstock#2, so hopefully a new version will be available soon.

**Comment by mgeier** [comment]
Thanks for the info, good to know.

You don't have to wait though, you can just do `python3 -m pip install nbsphinx`. It shouldn't be a problem to install things with `pip` in a `conda` environment.

If it doesn't work, tell me!

**Comment by jacobkolind** [comment]
Had thought of that, but yes you're right - `pip` will do just nicely. The upgrade to 0.2.13 solved my problem. Closing this issue.
